/*****************************************************************************
*    Copyright (C) 2008 ALi Corp. All Rights Reserved.
*
*    Company confidential and Properietary information.
*    This information may not be disclosed to unauthorized
*    individual.
*    File: winstyle1.h
*
*    Description:
*
*    History:
*    Date           Athor        Version        Reason
*    ========       ========     ========       ========
*    2008/12/2      Roman         1.0.0            Clear
*
*****************************************************************************/
#define SD_CLR     SST_SET_COLOR(OSD_256_COLOR)
#define HD_CLR     SST_SET_COLOR(OSD_HD_ARGB8888)
#define RGB_CLR(R,G,B)    (C_ALPHA0|((R)<<16)|((G)<<8)|(B))
#define HD_TRANS     C_ALPHA6
#define OSD_TRANSPARENT_COLOR_8BIT 0xFF

// 1. for the 32bit picture color,
// alpha == 0xff, no transparent.
// alpha == 0x00, full transparent.
// 2. for one color style color, such as fg / bg.
// set alpha by marco C_ALPHA0 - 1/2/3/4/5/6.

const WINSTYLE w_shstyle1[] __attribute__((section(".flash"))) =
{
/*  drawstyle                   topline     leftline        rightline       bottomline  background      frontground             */

/* WSTL_NOSHOW_IDX */
    {SD_CLR|C_WS_LINE_DRAW,C_NOSHOW,   C_NOSHOW,   C_NOSHOW,   C_NOSHOW,   C_NOSHOW,       C_MIXER | 0xF6,     INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX}, // Default, Do't change it : 0x00
/* WSTL_TRANS_IX */
    {SD_CLR|C_WS_LINE_DRAW,OSD_TRANSPARENT_COLOR, OSD_TRANSPARENT_COLOR, OSD_TRANSPARENT_COLOR,   OSD_TRANSPARENT_COLOR,   OSD_TRANSPARENT_COLOR,       C_MIXER | 0x60,     INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX}, // Default, Do't change it : 0x00
/* WSTL_TRANS_IX_HD */
//    {SD_CLR|C_WS_LINE_DRAW,OSD_TRANSPARENT_COLOR_8BIT, OSD_TRANSPARENT_COLOR_8BIT, OSD_TRANSPARENT_COLOR_8BIT,  OSD_TRANSPARENT_COLOR_8BIT,  OSD_TRANSPARENT_COLOR_8BIT,       C_MIXER | 0xF0,     INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX}, // Default, Do't change it : 0x00
/* Transparent color WSTL_TRANS_IX_HD_8BIT */
//    {SD_CLR|C_WS_LINE_DRAW,OSD_TRANSPARENT_COLOR_8BIT, OSD_TRANSPARENT_COLOR_8BIT, OSD_TRANSPARENT_COLOR_8BIT,   OSD_TRANSPARENT_COLOR_8BIT,   OSD_TRANSPARENT_COLOR_8BIT,       C_MIXER | 0x80,     INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX}, // Default, Do't change it : 0x00

/* WSTL_MIXBACK_BLACK_IDX, Noshow,Mix background,black foregound */
    {SD_CLR|C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW,    C_NOSHOW,   C_NOSHOW, C_NOSHOW | C_MIXER, C_MIXER | 0x74, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
/* WSTL_MIXBACK_WHITE_IDX, Noshow,Mix background,white foregound */
    {SD_CLR|C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW,    C_NOSHOW,   C_NOSHOW, C_NOSHOW | C_MIXER, C_MIXER | 0x61, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_WIN_TITLE_01_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_TITLE_BG,        IM_TITLE_LEFT,        IM_TITLE_RIGHT,        INVALID_INDEX,        C_NOSHOW,             C_MIXER | 0xF1,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_WIN_BODYRIGHT_01_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_MAINMENU_RIGHTWIN_TOP,        IM_MAINMENU_RIGHTWIN_LEFT,        IM_MAINMENU_RIGHTWIN_RIGHT,        IM_MAINMENU_RIGHTWIN_BOTTOM,    0xB1,        C_NOSHOW,        IM_MAINMENU_RIGHTWIN_LEFTTO,   IM_MAINMENU_RIGHTWIN_LEFTBO, IM_MAINMENU_RIGHTWIN_RIGHTT,   IM_MAINMENU_RIGHTWIN_RIGHTB, LIB_ICON},
//WSTL_WIN_BODYLEFT_01_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_MAINMENU_LEFTWIN_TOP,        IM_MAINMENU_LEFTWIN_LEFT,        IM_MAINMENU_LEFTWIN_RIGHT,        IM_MAINMENU_LEFTWIN_BOTTOM,    0xB1,        C_NOSHOW,        IM_MAINMENU_LEFTWIN_LEFTTOP,   IM_MAINMENU_LEFTWIN_LEFTBOT, IM_MAINMENU_LEFTWIN_RIGHTTO,   IM_MAINMENU_LEFTWIN_RIGH_13, LIB_ICON},
//WSTL_WIN_MAINMENU_01_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_WIN_08_T,        IM_WIN_08_L,        IM_WIN_08_R,        IM_WIN_08_B,    C_MIXER|0xAA,        C_NOSHOW,        IM_WIN_08_LT,   IM_WIN_08_LB, IM_WIN_08_RT,   IM_WIN_08_RB, LIB_ICON},
//WSTL_WIN_MAINMENU_01_BG_HD
    {SD_CLR|C_WS_LINE_DRAW,        0xAA,      0xAA,        0xAA,    0xAA,        0xAA,        0xAA,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_WINCHANNELIST_01_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_TITLE_BG,    IM_WIN_06_L,        IM_WIN_06_R,        IM_WIN_06_B,    0xB1,             C_MIXER | 0xA2,        IM_TITLE_LEFT,   IM_WIN_06_LB, IM_TITLE_RIGHT,   IM_WIN_06_RB, LIB_ICON},
//WSTL_VOLUME_01_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_VOLUME_BG,       INVALID_INDEX ,    INVALID_INDEX,    INVALID_INDEX,        C_TRANS_NODRAW|C_MIXER|0x0F,            C_MIXER | 0x0F,        IM_VOLUME_LEFT,    INVALID_INDEX,    IM_VOLUME_RIGHT, INVALID_INDEX, LIB_ICON},
//WSTL_VOLUME_01_BG_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_VOLUME_BG,        INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        0x0F,            C_MIXER | 0x0F,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_VOLUME_01_FG_HD
    {SD_CLR|C_WS_LINE_DRAW,            0x8D,        0x8D,        0x8D,        0x8D,        0x8D,            C_MIXER | 0x8D,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX},
//WSTL_VOLUME_02_FG
    {SD_CLR|C_WS_LINE_DRAW,        0x74,        0x74,        0x74,        0x74,        0x74,            C_MIXER | 0x74,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_AUDIO_WIN_01
    {SD_CLR|C_WS_PIC_DRAW,            INVALID_INDEX,       IM_GROUP_LEFT ,        IM_GROUP_RIGHT,        INVALID_INDEX,        C_MIXER | 0xB1,            C_MIXER | 0xF0,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_POP_WIN_01_HD
    {SD_CLR|C_WS_PIC_DRAW,IM_WINDOW_TITLE_BG,IM_WINDOW_MIDDLE_LEFT,IM_WINDOW_MIDDLE_RIGHT,IM_WINDOW_BOTTOM_BG,C_TRANS_NODRAW|C_MIXER|0xE8, C_MIXER | 0xF6,        IM_WINDOW_TITLE_LEFT,   IM_WINDOW_LEFTBOTTOM, IM_WINDOW_TITLE_RIGHT,   IM_WINDOW_BOTTOM_RIGHT, LIB_ICON},
//WSTL_WININFO_01_HD
//    {SD_CLR|C_WS_PIC_DRAW,            IM_TVCHANNELLIST_HELP_WIN_TOP,    IM_TVCHANNELLIST_HELP_WIN_LEFT,        IM_TVCHANNELLIST_HELP_WIN_RIGHT,        IM_TVCHANNELLIST_HELP_WIN_BOTTOM, 0xB1, C_MIXER | 0xF6,        IM_TVCHANNELLIST_HELP_WIN_LEFTTOP,   IM_TVCHANNELLIST_HELP_WIN_LEFTBOTTOM, IM_TVCHANNELLIST_HELP_WIN_RIGHTTOP,   IM_TVCHANNELLIST_HELP_WIN_RIGHTBOTTOM, LIB_ICON},
//WSTL_WINCHANNELIST_TEXT_T
    {SD_CLR|C_WS_PIC_DRAW,            IM_WIN_04_T,    IM_WIN_04_L,        IM_WIN_04_R,        INVALID_INDEX,        0xAA,             C_MIXER | 0xF0,        IM_WIN_04_LT,   INVALID_INDEX, IM_WIN_04_RT,   INVALID_INDEX, LIB_ICON},
//WSTL_WINCHANNELIST_TEXT_M
    {SD_CLR|C_WS_PIC_DRAW,            INVALID_INDEX,    IM_WIN_04_L,        IM_WIN_04_R,        INVALID_INDEX,        0xAA,             C_MIXER | 0xF0,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_WINCHANNELIST_TEXT_B
    {SD_CLR|C_WS_PIC_DRAW,            INVALID_INDEX,    IM_WIN_04_L,        IM_WIN_04_R,        IM_WIN_04_B,        0xAA,             C_MIXER | 0xF0,        INVALID_INDEX,   IM_WIN_04_LB, INVALID_INDEX,   IM_WIN_04_RB, LIB_ICON},
//    WSTL_WINSEARCH,
    {SD_CLR|C_WS_PIC_DRAW, IM_MAINMENU_SEARCHWIN_01_TOP, IM_MAINMENU_SEARCHWIN_01_LEFT, IM_MAINMENU_SEARCHWIN_02_RIGHT, IM_MAINMENU_SEARCHWIN_03_BOTTOM, 0xB1, C_MIXER |0xF0,IM_MAINMENU_SEARCHWIN_01_LEFTTOP,   IM_MAINMENU_SEARCHWIN_03_LEFTBOTTOM, IM_MAINMENU_SEARCHWIN_02_RIGHTTOP,    IM_MAINMENU_SEARCHWIN_03_RIGHTBOTTOM, LIB_ICON},
//    WSTL_WINSEARCH_01_HD,
    {SD_CLR|C_WS_PIC_DRAW,            IM_MAINMENU_SEARCHWIN_01_TOP,        IM_MAINMENU_SEARCHWIN_01_LEFT,        IM_MAINMENU_SEARCHWIN_01_RIGHT,        IM_MAINMENU_SEARCHWIN_01_BOTTOM,        0xB1,        C_MIXER | 0xF0,    IM_MAINMENU_SEARCHWIN_01_LEFTTOP,   IM_MAINMENU_SEARCHWIN_01_LEFTBOTTOM, IM_MAINMENU_SEARCHWIN_01_RIGHTTOP,   IM_MAINMENU_SEARCHWIN_01_RIGHTBOTTOM, LIB_ICON},
//    WSTL_WINSEARCH_02_HD,
    {SD_CLR|C_WS_PIC_DRAW,            IM_MAINMENU_SEARCHWIN_02_TOP,        IM_MAINMENU_SEARCHWIN_02_LEFT,        IM_MAINMENU_SEARCHWIN_02_RIGHT,        IM_MAINMENU_SEARCHWIN_02_BOTTOM,        0xB1,        C_MIXER | 0xF0,    IM_MAINMENU_SEARCHWIN_02_LEFTTOP,   IM_MAINMENU_SEARCHWIN_02_LEFTBOTTOM, IM_MAINMENU_SEARCHWIN_02_RIGHTTOP,   IM_MAINMENU_SEARCHWIN_02_RIGHTBOTTOM, LIB_ICON},
//    WSTL_WINSEARCH_03_HD,
    {SD_CLR|C_WS_PIC_DRAW,            IM_MAINMENU_SEARCHWIN_03_TOP,        IM_MAINMENU_SEARCHWIN_03_LEFT,        IM_MAINMENU_SEARCHWIN_03_RIGHT,        IM_MAINMENU_SEARCHWIN_03_BOTTOM,        0xB1,        C_MIXER | 0xF0,    IM_MAINMENU_SEARCHWIN_03_LEFTTOP,   IM_MAINMENU_SEARCHWIN_03_LEFTBOTTOM, IM_MAINMENU_SEARCHWIN_03_RIGHTTOP,   IM_MAINMENU_SEARCHWIN_03_RIGHTBOTTOM, LIB_ICON},
//WSTL_ZOOM_WIN_01_RECT
    {SD_CLR|C_WS_LINE_DRAW,          0x00, 0x00,    0x00,   0x00,  0xB1/*OSD_TRANSPARENT_COLOR_8BIT*/, 0xB1/*OSD_TRANSPARENT_COLOR_8BIT*/, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_KEYBOARD_01_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_KEYBOARD_BAR_MIDDLE,                IM_KEYBOARD_BAR_LEFT,            IM_KEYBOARD_BAR_RIGHT,        INVALID_INDEX,            C_MIXER | 0x59,        C_MIXER | 0xF2,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_SCROLLBAR_01_HD
    {SD_CLR|C_WS_PIC_DRAW,            INVALID_INDEX,        IM_SCROLL_BAR_BG,                INVALID_INDEX,        INVALID_INDEX,                C_NOSHOW,        C_NOSHOW,        IM_SCROLL_BAR_ARROW_TOP,   IM_SCROLL_BAR_ARROW_BOTTOM, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_SCROLLBAR_02_HD
    {SD_CLR|C_WS_PIC_DRAW,            INVALID_INDEX,            IM_SCROLL_SCROLL_MIDDLE,        INVALID_INDEX,        INVALID_INDEX,                C_NOSHOW,        C_NOSHOW,        IM_SCROLL_SCROLL_TOP,   IM_SCROLL_SCROLL_BOTTOM, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_01_HD
    {SD_CLR|C_WS_LINE_DRAW,        0xB1, 0xB1,     0xB1,   0xB1, 0xB1, C_MIXER|0xF0, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_BUTTON_01_FG_HD
    {SD_CLR|C_WS_LINE_DRAW,        C_NOSHOW,  C_NOSHOW,  C_NOSHOW,   C_NOSHOW, C_TRANS_NODRAW |C_NOSHOW |  C_MIXER, 0xF0, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_BUTTON_02_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_BUTTON_SELECT_M,        INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,                C_MIXER,        C_NOSHOW,        IM_BUTTON_SELECT_L,   INVALID_INDEX, IM_BUTTON_SELECT_R,   INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_02_FG_HD
    {SD_CLR|C_WS_LINE_DRAW,        C_NOSHOW,  C_NOSHOW,  C_NOSHOW,     C_NOSHOW,    C_NOSHOW |  C_MIXER, C_MIXER | 0xF6,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_03_HD
    {SD_CLR|C_WS_LINE_DRAW,        0xAA, 0xAA,     0xAA,   0xAA, 0xAA, C_MIXER|0xF0, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_BUTTON_03_FG_HD
    {SD_CLR|C_WS_LINE_DRAW,        C_NOSHOW,  C_NOSHOW,  C_NOSHOW,     C_NOSHOW,    C_NOSHOW |  C_MIXER, C_MIXER | 0xF1,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_04_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_BUTTON_SELECT_M,        IM_SELECT_LEFT,        IM_SELECT_RIGHT,        INVALID_INDEX,        0xB1,        C_MIXER | 0xF6,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_05_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_BUTTON_SELECT_M,        INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,                 C_TRANS_NODRAW |C_MIXER|0xB1,        C_MIXER | 0xF6,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_07_HD
    {SD_CLR|C_WS_LINE_DRAW,        0xB1, 0xB1,    0xB1,   0xB1, 0xB1, C_MIXER |0xF7, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_BUTTON_08_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_MULTIBUTTON_MIDDLE,        IM_MULTIBUTTON_LEFT,        IM_MULTIBUTTON_RIGHT,        INVALID_INDEX,              C_TRANS_NODRAW |C_MIXER|0xB1,        C_MIXER | 0xF6,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_10
//    {SD_CLR|C_WS_LINE_DRAW,          0xB1, 0xB1,    0xB1,   0xB1, 0xB1, C_MIXER | 0x74, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_BUTTON_11_HD
//    {HD_CLR|C_WS_LINE_DRAW,          0xB1, 0xB1,    0xB1,   0xB1, 0xB1, C_MIXER | RGB_CLR(0x3e,0x7b,0xb9), INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_KEYBOARDBUTTON_01_SH_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_KEYBOARD_ITEM,                    INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        0xB1,        C_MIXER |  0xF6,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_KEYBOARDBUTTON_01_HL_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_KEYBOARD_ITEM_SELECT,            INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        0x94,        C_MIXER | 0xF2,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_KEYBOARDBUTTON_02_SH_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_KEYBOARD_ITEM_BIG,                INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        0xB1,        C_MIXER |  0xF6,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_KEYBOARDBUTTON_02_HL_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_KEYBOARD_ITEM_BIG_SELECT,        INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        0x94,        C_MIXER | 0xF2,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTYL_COLBTN_RED
    {SD_CLR|C_WS_PIC_DRAW,            IM_COLORBUTTON_RED,                    INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        0xB1,         C_MIXER|0xEC,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTYL_COLBTN_RED_SELECT
    {SD_CLR|C_WS_PIC_DRAW,            IM_COLORBUTTON_RED_SELECT,            INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        0xB1,         C_MIXER|0xEC,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTYL_COLBTN_GREEN
    {SD_CLR|C_WS_PIC_DRAW,            IM_COLORBUTTON_GREEN,                INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        0xB1,         C_MIXER|0xEC,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTYL_COLBTN_GREEN_SELECT
    {SD_CLR|C_WS_PIC_DRAW,            IM_COLORBUTTON_GREEN_SELECT,        INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        0xB1,         C_MIXER|0xEC,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTYL_COLBTN_YELLOW
    {SD_CLR|C_WS_PIC_DRAW,            IM_COLORBUTTON_YELLOW,                INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        0xB1,         C_MIXER|0xEC,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTYL_COLBTN_YELLOW_SELECT
    {SD_CLR|C_WS_PIC_DRAW,            IM_COLORBUTTON_YELLOW_SELECT,        INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        0xB1,         C_MIXER|0xEC,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTYL_COLBTN_BLUE
    {SD_CLR|C_WS_PIC_DRAW,            IM_COLORBUTTON_BLUE,                INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        0xB1,         C_MIXER|0xEC,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTYL_COLBTN_BLUE_SELECT
    {SD_CLR|C_WS_PIC_DRAW,            IM_COLORBUTTON_BLUE_SELECT,            INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        0xB1,         C_MIXER|0xEC,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTYL_COLBTN_GRAY
    {SD_CLR|C_WS_PIC_DRAW,            IM_COLORBUTTON_GRAY,                INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        0xB1,         C_MIXER|0xEC,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTYL_COLBTN_GRAY_SELECT
    {SD_CLR|C_WS_PIC_DRAW,            IM_COLORBUTTON_GRAY_SELECT,            INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        0xB1,         C_MIXER|0xEC,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_POP_SH_HD
    {SD_CLR|C_WS_PIC_DRAW,IM_BUTTON_POP_01_M,  INVALID_INDEX,INVALID_INDEX,INVALID_INDEX,C_TRANS_NODRAW|C_MIXER|0xB1,C_MIXER | 0xF6,IM_BUTTON_POP_01_L,INVALID_INDEX, IM_BUTTON_POP_01_R,   INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_POP_HL_HD
    {SD_CLR|C_WS_PIC_DRAW,IM_BUTTON_POP_01_M_08,INVALID_INDEX,INVALID_INDEX,INVALID_INDEX, C_MIXER,C_MIXER | 0xF6,IM_BUTTON_POP_02_L,INVALID_INDEX, IM_BUTTON_POP_01_R_09,   INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_SHOR_HD,
    {SD_CLR|C_WS_PIC_DRAW,            IM_BUTTON_SHORT_MIDDLE, INVALID_INDEX,INVALID_INDEX,INVALID_INDEX,    C_MIXER|0xB1,C_MIXER | 0xF6,IM_BUTTON_SHORT_LEFT,   INVALID_INDEX, IM_BUTTON_SHORT_RIGHT,   INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_SHOR_HI_HD,
    {SD_CLR|C_WS_PIC_DRAW,            IM_BUTTON_SHORT_SELECT_MIDDLE,INVALID_INDEX,  INVALID_INDEX, INVALID_INDEX, C_MIXER|0xB1,C_MIXER | 0xF6,    IM_BUTTON_SHORT_SELECT_LEFT,INVALID_INDEX, IM_BUTTON_SHORT_SELECT_RIGHT, INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_SHOR_GRY_HD,
    {SD_CLR|C_WS_PIC_DRAW,            IM_BUTTON_SHORT_MIDDLE,INVALID_INDEX,INVALID_INDEX,INVALID_INDEX,    C_TRANS_NODRAW|0xB1,C_MIXER | 0xF6, IM_BUTTON_SHORT_LEFT, INVALID_INDEX,IM_BUTTON_SHORT_RIGHT, INVALID_INDEX, LIB_ICON},
//    WSTL_BARBG_01
    {SD_CLR|C_WS_PIC_DRAW,            IM_SIGNALBG_MIDDLE,        IM_SIGNALBG_LEFT,        IM_SIGNALBG_RIGHT,            INVALID_INDEX,      C_MIXER | 0x8D,        C_MIXER | 0x74,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//    WSTL_BAR_06
    {SD_CLR|C_WS_PIC_DRAW,          IM_SIGNAL_BLUE_MIDDLE, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX,         0x8D,       C_MIXER | 0x74,     IM_SIGNAL_BLUE_LEFT,      INVALID_INDEX,IM_SIGNAL_BLUE_RIGHT, INVALID_INDEX, LIB_ICON},
//WSTL_TEXT_04_HD
    {SD_CLR|C_WS_LINE_DRAW,        0xE8,  0xE8,  0xE8,   0xE8, 0xE8, 0xF0, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_08_HD,
    {SD_CLR|C_WS_LINE_DRAW,        0xB1, 0xB1, 0xB1, 0xB1, 0xB1 , C_MIXER | 0xF0, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_09_HD,
    {SD_CLR|C_WS_LINE_DRAW,        0xB1, 0xB1, 0xB1, 0xB1, 0xB1 , C_MIXER | 0xF0, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_10_HD,
    {SD_CLR|C_WS_LINE_DRAW,        OSD_TRANSPARENT_COLOR_8BIT, OSD_TRANSPARENT_COLOR_8BIT, OSD_TRANSPARENT_COLOR_8BIT, OSD_TRANSPARENT_COLOR_8BIT, OSD_TRANSPARENT_COLOR_8BIT , C_MIXER | 0xB1, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_11_HD,
    {SD_CLR|C_WS_PIC_DRAW,            INVALID_INDEX,        IM_GROUP_LEFT,        IM_GROUP_RIGHT,        INVALID_INDEX, 0xB1 | C_MIXER,C_MIXER|0xF0,INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_TEXT_13_HD,
//    {HD_CLR|C_WS_LINE_DRAW,        C_ALPHA5|RGB_CLR(0,0,0),C_ALPHA5|RGB_CLR(0,0,0),C_ALPHA5|RGB_CLR(0,0,0), C_ALPHA5|RGB_CLR(0,0,0),C_ALPHA5|RGB_CLR(0,0,0),C_MIXER |0xF0, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_TRANS_11_HD
    {SD_CLR|C_WS_PIC_DRAW,            INVALID_INDEX,        IM_GROUP_LEFT,        IM_GROUP_RIGHT,        INVALID_INDEX, C_TRANS_NODRAW|0xAA | C_MIXER,C_MIXER|0xF0,INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_TEXT_13,
    {SD_CLR|C_WS_LINE_DRAW,        0XBC, 0XBC, 0XBC, 0XBC, 0XBC , C_MIXER | 0x71, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_14,
    {SD_CLR|C_WS_LINE_DRAW,        0XBC, 0XBC, 0XBC, 0XBC, 0XBC , C_MIXER | 0xD9, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_20_HD
    {SD_CLR|C_WS_LINE_DRAW,        0xE8,  0xE8,  0xE8,   0xE8, 0xE8,    C_MIXER|0xF7, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_25
    {SD_CLR|C_WS_LINE_DRAW,         0XB7,  0XB7,  0XB7,  0XB7,  0XB7 , C_MIXER | 0x74, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_26
    {SD_CLR|C_WS_LINE_DRAW,         0XB7,  0XB7,  0XB7,  0XB7,  0XB7 , C_MIXER | 0x71, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_GAMEWIN_01_HD
    {SD_CLR|C_WS_PIC_DRAW,     IM_GAME_WIN_01_TOP,     IM_GAME_WIN_01_LEFT,    IM_GAME_WIN_01_RIGHT,    IM_GAME_WIN_01_BOTTOM,   0xB1,        C_NOSHOW,        IM_GAME_WIN_01_LEFTTOP,  IM_GAME_WIN_01_LEFTBOTTOM, IM_GAME_WIN_01_RIGHTTOP,   IM_GAME_WIN_01_RIGHTBOTTOM, LIB_ICON},
//WSTL_GAMESUDOKU_NORMAL1_HD
    {SD_CLR|C_WS_LINE_DRAW,         0xEF,  0xEF,  0xEF,  0xEF,  0xD3 , C_MIXER | 0xF2, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_GAMESUDOKU_NORMAL2_HD
    {SD_CLR|C_WS_LINE_DRAW,        0xEF, 0xEF, 0xEF, 0xEF, 0xD5 , C_MIXER | 0xF2, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_GAMESUDOKU_FIX_HD
    {SD_CLR|C_WS_LINE_DRAW,        0xEF, 0xEF, 0xEF, 0xEF, 0xC3 , C_MIXER | 0xF2, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_GAMESUDOKU_CURSOR_HD
    {SD_CLR|C_WS_LINE_DRAW,        0xF6, 0xF6, 0xF6, 0xF6, 0x94 , C_MIXER | 0xF6, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_07,
    {SD_CLR|C_WS_LINE_DRAW,        OSD_TRANSPARENT_COLOR_8BIT, OSD_TRANSPARENT_COLOR_8BIT, OSD_TRANSPARENT_COLOR_8BIT, OSD_TRANSPARENT_COLOR_8BIT, OSD_TRANSPARENT_COLOR_8BIT , C_MIXER | 0xF2, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_06,
    {SD_CLR|C_WS_LINE_CIRCL_DRAW,  0x71, 0x71, 0x71, 0x71, OSD_TRANSPARENT_COLOR_8BIT , C_MIXER | 0x71, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_MP_PREV_01
    {SD_CLR|C_WS_LINE_DRAW,        0xB1|C_DOUBLE_LINE, 0xB1|C_DOUBLE_LINE, 0xB1|C_DOUBLE_LINE, 0xB1|C_DOUBLE_LINE, OSD_TRANSPARENT_COLOR , C_MIXER | 0x71, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_MP_PREV_02
    {SD_CLR|C_WS_LINE_DRAW,        0x94|C_DOUBLE_LINE, 0x94|C_DOUBLE_LINE, 0x94|C_DOUBLE_LINE, 0x94|C_DOUBLE_LINE, OSD_TRANSPARENT_COLOR , C_MIXER | 0x71, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},


/* WSTL_MIXBACK_BLACK_IDX_HD, Noshow,Mix background,black foregound */
    {SD_CLR|C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW,    C_NOSHOW,   C_NOSHOW, C_NOSHOW | C_MIXER, C_MIXER | 0xF6, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
/* WSTL_MIXBACK_WHITE_IDX_HD, Noshow,Mix background,white foregound */
    {SD_CLR|C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW,    C_NOSHOW,   C_NOSHOW, C_NOSHOW | C_MIXER, C_MIXER | 0xF0, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
// WSTL_LINE_HD
    {SD_CLR|C_WS_LINE_DRAW,        0xE2,      0xE2,        0xE2,    0xE2,        0xE2,        0xE2,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
// WSTL_LINE_MENU_HD
    {SD_CLR|C_WS_LINE_DRAW,        0xE1,      0xE1,        0xE1,    0xE1,        0xE1,        0xE1,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_TEXT_01_HD
    {SD_CLR|C_WS_LINE_DRAW,          0x95, 0xE2, 0x95, 0x95,  C_MIXER|0x95,  C_MIXER | 0xF6, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_02_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_BUTTON_SELECT_M,        IM_EPG_LINE_01,        INVALID_INDEX,        INVALID_INDEX,                INVALID_INDEX,        C_MIXER | 0xF6,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_TEXT_03_HD
    {SD_CLR|C_WS_LINE_DRAW,        C_NOSHOW, C_NOSHOW, C_NOSHOW,    C_NOSHOW, 0xE8,        C_MIXER | 0xF6,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_05_HD,
    {SD_CLR|C_WS_LINE_DRAW,        0xB1, 0xB1, 0xB1, 0xB1, OSD_TRANSPARENT_COLOR_8BIT , C_MIXER | 0xB1, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_06_HD
    {SD_CLR|C_WS_PIC_DRAW,            INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,                IM_EPG_TEXT_BG_01,        C_MIXER | 0xF0,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_TEXT_07_HD,
    {SD_CLR|C_WS_LINE_DRAW,        C_NOSHOW, C_NOSHOW,C_NOSHOW,C_NOSHOW,OSD_TRANSPARENT_COLOR_8BIT, C_MIXER | 0xEC, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_12_HD
    {SD_CLR|C_WS_LINE_DRAW,        C_NOSHOW, C_NOSHOW, C_NOSHOW,    C_NOSHOW, C_NOSHOW,        C_MIXER | 0xF6,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_21_HD
    {SD_CLR|C_WS_LINE_DRAW,        0xB1,  0xB1,  0xB1,  0xB1,  0xB1 , C_MIXER | 0xF6, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_22_HD
    {SD_CLR|C_WS_PIC_DRAW,            INVALID_INDEX,        IM_MEDIAPLAY_GROUPARROW_L,        IM_MEDIAPLAY_GROUPARROW_R,        INVALID_INDEX,                INVALID_INDEX,        C_MIXER | 0xF6,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_TEXT_23_HD
    {SD_CLR|C_WS_LINE_DRAW,         C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0xAA, C_MIXER|0xF0,INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_24_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_TITLE_BG,        INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,                INVALID_INDEX,        C_MIXER | 0xF1,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_TEXT_25_HD
    {SD_CLR|C_WS_LINE_DRAW,        0xB1,  0xB1,  0xB1,  0xB1,  0xB1 , C_MIXER | 0xF0, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_26_HD
    {SD_CLR|C_WS_LINE_DRAW,         0xB1,  0xB1,  0xB1,  0xB1,  0xB1 , C_MIXER | 0xB1, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_27_HD,
    {SD_CLR|C_WS_PIC_DRAW,         IM_BUTTON_EPG_01_MIDDLE,    IM_BUTTON_EPG_01_LEFT,    IM_BUTTON_EPG_01_RIGHT, INVALID_INDEX,INVALID_INDEX,       C_MIXER | 0xF6,      INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_TEXT_28_HD,
    {SD_CLR|C_WS_PIC_DRAW,            IM_SLIST_WIN_TOP,        IM_SLIST_WIN_LEFTTOP,        IM_SLIST_WIN_RIGHTTOP,        INVALID_INDEX,                INVALID_INDEX,        C_MIXER | 0xB1,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_WIN_EPG_LINE_01_HD
    {SD_CLR|C_WS_PIC_DRAW,         INVALID_INDEX,      IM_EPG_LINE_01,      INVALID_INDEX,      INVALID_INDEX,              C_NOSHOW,        C_MIXER | 0xF0,      INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_WIN_EPG_01_HD
    {SD_CLR|C_WS_PIC_DRAW,          IM_WIN_04_T, IM_WIN_04_L, IM_WIN_04_R, IM_WIN_04_B,  0xAA,   0xF6, IM_WIN_04_LT, IM_WIN_04_LB, IM_WIN_04_RT, IM_WIN_04_RB, LIB_ICON},
//WSTL_WIN_EPG_02_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_EPG_TEXT_BG_01,        INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,                0xAA,        C_MIXER | 0xF0,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_WIN_EPG_HELP_HD
    {SD_CLR|C_WS_LINE_DRAW,          0x95, 0x95, 0x95, 0x95,  C_MIXER|0x95,  C_MIXER | 0xF6, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//    WSTL_BARBG_01_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_SIGNALBG_MIDDLE,        INVALID_INDEX,        INVALID_INDEX,            INVALID_INDEX,      C_MIXER,        C_MIXER | 0xB1,        IM_SIGNALBG_LEFT,   INVALID_INDEX, IM_SIGNALBG_RIGHT,   INVALID_INDEX, LIB_ICON},
//    WSTL_BAR_01_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_SIGNAL_BLUE_MIDDLE,    IM_SIGNAL_BLUE_LEFT,    IM_SIGNAL_BLUE_RIGHT,        INVALID_INDEX,                C_TRANS_NODRAW|0xB1,        C_MIXER | 0xF6,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//    WSTL_BAR_02_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_SIGNAL_GREEN_MIDDLE,    IM_SIGNAL_GREEN_LEFT,    IM_SIGNAL_GREEN_RIGHT,        INVALID_INDEX,                C_TRANS_NODRAW|0xB1,        C_MIXER | 0xF6,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//    WSTL_BAR_03_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_SIGNAL_GRAY_MIDDLE,    IM_SIGNAL_GRAY_LEFT,    IM_SIGNAL_GRAY_RIGHT,        INVALID_INDEX,                C_TRANS_NODRAW|0xB1,        C_MIXER | 0xF6,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//    WSTL_BAR_04_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_SIGNAL_ORANGE_MIDDLE,IM_SIGNAL_ORANGE_LEFT,    IM_SIGNAL_ORANGE_RIGHT,        INVALID_INDEX,                C_TRANS_NODRAW|0xB1,        C_MIXER | 0xF6,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//    WSTL_MIX_BMP_HD,
    {SD_CLR|C_WS_LINE_DRAW,    C_NOSHOW,C_NOSHOW,C_NOSHOW,C_NOSHOW,C_NOSHOW|C_MIXER,C_NOSHOW|C_MIXER,INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//    WSTL_POP_MIX_BMP_HD,
    {SD_CLR|C_WS_LINE_DRAW,    0xE8,0xE8,0xE8,0xE8,0xE8,C_NOSHOW|C_MIXER,INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//    WSTL_POP_TXT_SH_HD,
    {SD_CLR|C_WS_LINE_DRAW, C_NOSHOW,C_NOSHOW,C_NOSHOW,C_NOSHOW,C_MIXER|C_NOSHOW, 0xF0, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//  WSTL_POP_TXT_TITLE_HD
    {SD_CLR|C_WS_PIC_DRAW, IM_WINDOW_TITLE_BG,INVALID_INDEX,INVALID_INDEX,INVALID_INDEX,C_TRANS_NODRAW|C_MIXER|0xE8, 0xF0, IM_WINDOW_TITLE_LEFT, INVALID_INDEX, IM_WINDOW_TITLE_RIGHT, INVALID_INDEX, LIB_ICON},
//    WSTL_POP_TXT_SH_01_HD,
    {SD_CLR|C_WS_LINE_DRAW, C_NOSHOW,C_NOSHOW,C_NOSHOW,C_NOSHOW,C_MIXER|0xE8, 0xF0, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//    WSTL_PREV_01_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_WIN_PV_T,    IM_WIN_PV_L,        IM_WIN_PV_R,        IM_WIN_PV_B,            OSD_TRANSPARENT_COLOR_8BIT,                C_MIXER | 0xF2,        IM_WIN_PV_LT,   IM_WIN_PV_LB, IM_WIN_PV_RT,   IM_WIN_PV_RB, LIB_ICON},
//  WSTL_MP3_BAR01_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_MEDIAPLAY_BAR_01_MIDDLE,  IM_MEDIAPLAY_BAR_01_MIDDLE,    IM_MEDIAPLAY_BAR_01_MIDDLE/*IM_MEDIAPLAY_BAR_01_RIGHT*/,        INVALID_INDEX,          INVALID_INDEX     ,    INVALID_INDEX,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
// WSTL_POP_LINE_HD
    {SD_CLR|C_WS_LINE_DRAW,    0xE2,0xE2,0xE2,0xE2,0xE2,0xE2,INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_SELECT_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_BUTTON_SELECT_M,        INVALID_INDEX,        IM_SELECT_RIGHT,        INVALID_INDEX,              C_MIXER|0xB1,        C_MIXER | 0xF6,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_MP_WIN_MIDDLE_HD,
    {SD_CLR|C_WS_PIC_DRAW,            INVALID_INDEX,        IM_WIN_06_L,        IM_WIN_06_R,        INVALID_INDEX,          0xB1,        C_MIXER|0xF6,        INVALID_INDEX,  INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_MP_WIN_BOTTOM_HD,
    {SD_CLR|C_WS_PIC_DRAW,            INVALID_INDEX,        IM_WIN_06_L,        IM_WIN_06_R,        IM_WIN_06_B,          0xB1,        C_MIXER|0xF6,        INVALID_INDEX,  IM_WIN_06_LB, INVALID_INDEX,   IM_WIN_06_RB, LIB_ICON},
//WSTL_MP_HELP_HD,
    {SD_CLR|C_WS_PIC_DRAW,            IM_WIN_05_T, IM_WIN_05_L,    IM_WIN_05_R,        IM_WIN_05_B,          C_MIXER,        C_NOSHOW,        IM_WIN_05_LT,  IM_WIN_05_LB, IM_WIN_05_RT,   IM_WIN_05_RB, LIB_ICON},
//WSTL_MP_BUTTON_02_HD
//    {SD_CLR|C_WS_PIC_DRAW,            IM_MEDIAPLAY_BUTTON_01_M, IM_MEDIAPLAY_BUTTON_01_L,    IM_MEDIAPLAY_BUTTON_01_R,    INVALID_INDEX,    0xB1 , C_MIXER|0xF6,    INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
    {SD_CLR|C_WS_PIC_DRAW,            IM_BUTTON_POP_01_M, IM_BUTTON_POP_01_L,    IM_BUTTON_POP_01_R,    INVALID_INDEX,    0xB1 , C_MIXER|0xF6,    INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MP_BARBG_01_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_MEDIAPLAY_RATEBG_01,        INVALID_INDEX,        INVALID_INDEX,            INVALID_INDEX,      C_MIXER | 0xB1,        C_MIXER | 0xF6,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_MP_PREV_01_HD
    {SD_CLR|C_WS_LINE_DRAW,        0xB1|C_DOUBLE_LINE, 0xB1|C_DOUBLE_LINE, 0xB1|C_DOUBLE_LINE, 0xB1|C_DOUBLE_LINE, OSD_TRANSPARENT_COLOR_8BIT, C_MIXER | 0xF6, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_MP_PREV_02_HD
    {SD_CLR|C_WS_LINE_DRAW,        0xF6|C_DOUBLE_LINE, 0xF6|C_DOUBLE_LINE, 0xF6|C_DOUBLE_LINE, 0xF6|C_DOUBLE_LINE, OSD_TRANSPARENT_COLOR_8BIT, C_MIXER | 0xF0, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_MP_DEV_SH_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_MEDIAPLAY_USBBAR_M,    IM_MEDIAPLAY_USBBAR_L,        IM_MEDIAPLAY_USBBAR_R,        INVALID_INDEX,        C_MIXER|0xAA,             C_MIXER | 0xF0,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_MP_DEV_HL_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_BUTTON_MEDIAPLAY_01_M,    IM_BUTTON_MEDIAPLAY_01_L,    IM_BUTTON_MEDIAPLAY_01_R,        INVALID_INDEX,        C_MIXER|0xAA,             C_MIXER | 0xF0,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_MP_DEV_TXT_HD
    {SD_CLR|C_WS_PIC_DRAW,            INVALID_INDEX, IM_GROUP_LEFT, IM_GROUP_RIGHT, INVALID_INDEX,  C_NOSHOW | C_MIXER, C_MIXER | 0xF6, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MP_SPCTRM_GRAY_HD
    {SD_CLR|C_WS_PIC_DRAW,        INVALID_INDEX, INVALID_INDEX,INVALID_INDEX,INVALID_INDEX, IM_SPECTRAM_GRAY,    C_MIXER | 0xF6,    INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MP_SPCTRM_BAR_HD
    {SD_CLR|C_WS_PIC_DRAW,INVALID_INDEX, INVALID_INDEX,INVALID_INDEX,INVALID_INDEX, IM_SPECTRAM_02_BLUE_M,    C_MIXER | 0xF6, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_CHAN_PREVIEW_INPUT_HD
    {SD_CLR|C_WS_PIC_DRAW,IM_NUMBER_S, INVALID_INDEX,INVALID_INDEX,INVALID_INDEX,  C_NOSHOW,    C_MIXER | 0xF1,    INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, LIB_ICON},
//WSTL_MP_DIR_HD
    {SD_CLR|C_WS_PIC_DRAW,          IM_WIN_07_T, IM_WIN_07_L, IM_WIN_07_R, IM_WIN_07_B, 0xE2, C_MIXER|0xF7,IM_WIN_07_LT, IM_WIN_07_LB, IM_WIN_07_RT, IM_WIN_07_RB, LIB_ICON},
//WSTL_MP_DIR_TXT_HD
    {SD_CLR|C_WS_LINE_DRAW,          0xE2, 0xE2, 0xE2, 0xE2,  0xE2,  C_MIXER | 0xF7, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_MP_MUTE_BG_HD
    {SD_CLR|C_WS_LINE_DRAW,        0x00,  0x00,  0x00,   0x00, 0x00,0x00, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_MP_POP_WIN_01_HD
    {SD_CLR|C_WS_PIC_DRAW,            IM_MEDIAPLAY_POPWIN_01_T, IM_MEDIAPLAY_POPWIN_01_L,IM_MEDIAPLAY_POPWIN_01_R,IM_MEDIAPLAY_POPWIN_01_B,C_MIXER|0xAA, C_MIXER | 0xF6,        IM_MEDIAPLAY_POPWIN_01_LT,   IM_MEDIAPLAY_POPWIN_01_LB, IM_MEDIAPLAY_POPWIN_01_RT,   IM_MEDIAPLAY_POPWIN_01_RB, LIB_ICON},
//WSTL_MP_HELP_GRY
    {SD_CLR|C_WS_LINE_DRAW,          0x95, 0x95, 0x95, 0x95,  C_MIXER|0x95,  C_MIXER | 0xF7, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},

//WSTL_INFO_01_8BIT
    {SD_CLR|C_WS_PIC_DRAW,            IM_SINGAL_BAR_E_BG,        IM_SINGAL_BAR_E_LEFT,        IM_SINGAL_BAR_E_RIGHT,        INVALID_INDEX,        0xB1,            C_MIXER | 0x62,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
/* Noshow,Mix background,black foregound */
    {SD_CLR|C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW,    C_NOSHOW,   C_NOSHOW, C_NOSHOW | C_MIXER, C_MIXER | 0xF0, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
/* Noshow,Mix background,white foregound */
    {SD_CLR|C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW,    C_NOSHOW,   C_NOSHOW, C_NOSHOW | C_MIXER, C_MIXER | 0xF1, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
/* Noshow,Mix background,white foregound */
    {SD_CLR|C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW,    C_NOSHOW,   C_NOSHOW, C_NOSHOW | C_MIXER, C_MIXER | 0xF2, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
/* Noshow,Mix background,white foregound */
    {SD_CLR|C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW,    C_NOSHOW,   C_NOSHOW, C_NOSHOW | C_MIXER, C_MIXER | 0xF3, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
/* Noshow,Mix background,white foregound */
    {SD_CLR|C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW,    C_NOSHOW,   C_NOSHOW, C_NOSHOW | C_MIXER, C_MIXER | 0xF4, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
/* Noshow,Mix background,white foregound */
    {SD_CLR|C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW,    C_NOSHOW,   C_NOSHOW, C_NOSHOW | C_MIXER, C_MIXER | 0xF5, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
/* Noshow,Mix background,black foregound */
    {SD_CLR|C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW,    C_NOSHOW,   C_NOSHOW, C_NOSHOW | C_MIXER, C_MIXER | 0xF6, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
/* Noshow,Mix background,black foregound */
    {SD_CLR|C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW,    C_NOSHOW,   C_NOSHOW, C_NOSHOW | C_MIXER, C_MIXER | 0xF7, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_INFO_CHINPUT_01_8BIT
    {SD_CLR|C_WS_PIC_DRAW,            IM_NUMBER,        INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        C_NOSHOW,            C_MIXER | 0xF0,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_VOLUME_01_8BIT
    {SD_CLR|C_WS_PIC_DRAW,            IM_VOLUME_BG,        IM_VOLUME_LEFT,        IM_VOLUME_RIGHT,        INVALID_INDEX,        0xBF,            C_MIXER | 0xBF,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_VOLUME_01_BG_8BIT
    {SD_CLR|C_WS_PIC_DRAW,            IM_VOLUME_BG,        INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        0x95,            C_MIXER | 0x95,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_VOLUME_01_FG_8BIT
    {SD_CLR|C_WS_LINE_DRAW,        0x74,        0x74,        0x74,        0x74,        0x74,            C_MIXER | 0x74,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_POP_WIN_01_8BIT
    {SD_CLR|C_WS_PIC_DRAW,            IM_WINDOW_TITLE_BG,        IM_WINDOW_MIDDLE_LEFT,        IM_WINDOW_MIDDLE_RIGHT,        IM_WINDOW_BOTTOM_BG,        0xE8 | C_MIXER,        C_MIXER | 0xF2,        IM_WINDOW_TITLE_LEFT,   IM_WINDOW_LEFTBOTTOM, IM_WINDOW_TITLE_RIGHT,   IM_WINDOW_BOTTOM_RIGHT, LIB_ICON},
//WSTL_TEXT_04_8BIT
    {SD_CLR|C_WS_LINE_DRAW,        0xE8, 0xE8, 0xE8,    0xE8, 0xE8 | C_MIXER,        C_MIXER |0xF4,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX},
//WSTL_KEYBOARD_01_8BIT
    {SD_CLR|C_WS_PIC_DRAW,            IM_KEYBOARD_BAR_MIDDLE,                INVALID_INDEX,            INVALID_INDEX,        INVALID_INDEX,        C_MIXER | 0xE8,        C_MIXER | 0xF2,        IM_KEYBOARD_BAR_LEFT,   INVALID_INDEX, IM_KEYBOARD_BAR_RIGHT,   INVALID_INDEX, LIB_ICON},
//WSTL_KEYBOARDBUTTON_01_SH_8BIT
    {SD_CLR|C_WS_PIC_DRAW,            IM_KEYBOARD_ITEM,                    INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        C_MIXER | 0xE8,        C_MIXER | 0xF0,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_KEYBOARDBUTTON_01_HL_8BIT
    {SD_CLR|C_WS_PIC_DRAW,            IM_KEYBOARD_ITEM_SELECT,            INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        C_MIXER | 0xE8,        C_MIXER | 0xF6,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_KEYBOARDBUTTON_02_SH_8BIT
    {SD_CLR|C_WS_PIC_DRAW,            IM_KEYBOARD_ITEM_BIG,                    INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        C_MIXER | 0xE8,        C_MIXER | 0xF0,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_KEYBOARDBUTTON_02_HL_8BIT
    {SD_CLR|C_WS_PIC_DRAW,            IM_KEYBOARD_ITEM_BIG_SELECT,            INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,        C_MIXER | 0xE8,      C_MIXER | 0xF6,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_WIN_SLIST_01_8BIT
    {SD_CLR|C_WS_PIC_DRAW,            IM_SLIST_WIN_TOP,    IM_SLIST_WIN_LEFT,        IM_SLIST_WIN_RIGHT,        IM_SLIST_WIN_BOTTOM,            0xB1,                C_MIXER | 0xF0,        IM_SLIST_WIN_LEFTTOP,   IM_SLIST_WIN_LEFTBOTTOM, IM_SLIST_WIN_RIGHTTOP,   IM_SLIST_WIN_RIGHTBOTTOM, LIB_ICON},
//WSTL_WIN_SLIST_02_8BIT
    {SD_CLR|C_WS_PIC_DRAW,            IM_SLIST_WIN_TOP,    IM_SLIST_WIN_LEFT,        IM_SLIST_WIN_RIGHT,        IM_WIN_06_B,            0xB1,                C_MIXER | 0xF0,        IM_SLIST_WIN_LEFTTOP_NA,   IM_WIN_06_LB, IM_SLIST_WIN_RIGHTTOP_NA,   IM_WIN_06_RB, LIB_ICON},
//WSTL_TEXT_16_8BIT
    {SD_CLR|C_WS_PIC_DRAW,            IM_SLIST_WIN_TOP,        INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,          C_NOSHOW,        C_MIXER | 0xF1,     INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
 //WSTL_BUTTON_05_8BIT
     {SD_CLR|C_WS_PIC_DRAW,            IM_BUTTON_SELECT_M,        INVALID_INDEX,        INVALID_INDEX,        INVALID_INDEX,                C_MIXER,        C_MIXER | 0xF6,        IM_BUTTON_SELECT_L,   INVALID_INDEX, IM_BUTTON_SELECT_R,   INVALID_INDEX, LIB_ICON},
//WSTL_TEXT_15_8BIT
    {SD_CLR|C_WS_LINE_DRAW,        0xB1, 0xB1, 0xB1, 0xB1, 0xB1/*0xB1|C_MIXER*/, C_MIXER | 0xF0, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_01_8BIT
    {SD_CLR|C_WS_LINE_DRAW,        C_NOSHOW,C_NOSHOW,C_NOSHOW,C_NOSHOW,0x95, C_MIXER | 0xF4, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_28_8BIT
    {SD_CLR|C_WS_LINE_DRAW,        C_NOSHOW,C_NOSHOW,C_NOSHOW,C_NOSHOW,C_NOSHOW|C_MIXER, C_MIXER | 0xF6, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_29_8BIT
    {SD_CLR|C_WS_LINE_DRAW,        0xF2,C_NOSHOW,C_NOSHOW,C_NOSHOW,0x95, C_MIXER | 0xF6, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_TEXT_30_8BIT
    {SD_CLR|C_WS_LINE_DRAW,        C_NOSHOW,C_NOSHOW,C_NOSHOW,C_NOSHOW, 0xE8|C_MIXER, C_MIXER | 0xF0, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_SCROLLBAR_01_8BIT
    {SD_CLR|C_WS_PIC_DRAW,            INVALID_INDEX,        IM_SCROLL_BAR_BG,                INVALID_INDEX,        INVALID_INDEX,               C_MIXER ,        C_NOSHOW,        IM_SCROLL_BAR_ARROW_TOP,   IM_SCROLL_BAR_ARROW_BOTTOM, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_SCROLLBAR_02_8BIT
    {SD_CLR|C_WS_PIC_DRAW,            INVALID_INDEX,            IM_SCROLL_SCROLL_MIDDLE,        INVALID_INDEX,        INVALID_INDEX,                C_MIXER,        C_NOSHOW,        IM_SCROLL_SCROLL_TOP,   IM_SCROLL_SCROLL_BOTTOM, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_POP_WIN_02_8BIT
    {SD_CLR|C_WS_PIC_DRAW,            IM_WINDOW_TITLE_BG,        IM_WINDOW_MIDDLE_LEFT,        IM_WINDOW_MIDDLE_RIGHT,        IM_WINDOW_BOTTOM_BG,        0xE8 | C_MIXER,        C_MIXER | 0xF0,        IM_WINDOW_TITLE_LEFT,   IM_WINDOW_LEFTBOTTOM, IM_WINDOW_TITLE_RIGHT,   IM_WINDOW_BOTTOM_RIGHT, LIB_ICON},
//WSTL_POP_LINE_8BIT
//    {SD_CLR|C_WS_PIC_DRAW,            IM_LINE_POP_01_M,  IM_LINE_POP_01_L,    IM_LINE_POP_01_R,        INVALID_INDEX,          C_MIXER|0xE8, C_MIXER | 0xF4,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_MAINMENU_LINE_8BIT
//    {SD_CLR|C_WS_PIC_DRAW,            IM_MAINMENU_LINE_M,        IM_MAINMENU_LINE_L,        IM_MAINMENU_LINE_R,        INVALID_INDEX,        0xB1,        C_MIXER | 0x62,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_BARBG_01_8BIT
    {SD_CLR|C_WS_PIC_DRAW,            IM_SIGNALBG_MIDDLE,        INVALID_INDEX,        INVALID_INDEX,            INVALID_INDEX,C_MIXER |0xE8,        C_MIXER | 0x74,        IM_SIGNALBG_LEFT,   INVALID_INDEX, IM_SIGNALBG_RIGHT,   INVALID_INDEX, LIB_ICON},
//    WSTL_BAR_01_8BIT
    {SD_CLR|C_WS_PIC_DRAW,            IM_SIGNAL_BLUE_MIDDLE,    IM_SIGNAL_BLUE_LEFT,    IM_SIGNAL_BLUE_RIGHT,        INVALID_INDEX,                0x8D,        C_MIXER | 0x74,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//    WSTL_BAR_02_8BIT
    {SD_CLR|C_WS_PIC_DRAW,            IM_SIGNAL_GREEN_MIDDLE,    IM_SIGNAL_GREEN_LEFT,    IM_SIGNAL_GREEN_RIGHT,        INVALID_INDEX,                0x8D,        C_MIXER | 0x74,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//    WSTL_BAR_03_8BIT
    {SD_CLR|C_WS_PIC_DRAW,            IM_SIGNAL_GRAY_MIDDLE,    IM_SIGNAL_GRAY_LEFT,    IM_SIGNAL_GRAY_RIGHT,        INVALID_INDEX,                0x8D,        C_MIXER | 0x74,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//    WSTL_BAR_04_8BIT
    {SD_CLR|C_WS_PIC_DRAW,            IM_SIGNAL_ORANGE_MIDDLE,IM_SIGNAL_ORANGE_LEFT,    IM_SIGNAL_ORANGE_RIGHT,        INVALID_INDEX,                0x8D,        C_MIXER | 0x74,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_POP_TEXT_8BIT
    {SD_CLR|C_WS_LINE_DRAW,            C_NOSHOW,        C_NOSHOW,        C_NOSHOW,        C_NOSHOW,                C_NOSHOW| C_MIXER,        C_MIXER | 0xF4,        INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_POP_SH_8BIT
    {SD_CLR|C_WS_PIC_DRAW, IM_BUTTON_POP_01_M,INVALID_INDEX,INVALID_INDEX,INVALID_INDEX,    C_MIXER,    C_MIXER |0xF6,IM_BUTTON_POP_01_L,INVALID_INDEX, IM_BUTTON_POP_01_R,   INVALID_INDEX, LIB_ICON},
//WSTL_BUTTON_POP_HL_8BIT
     {SD_CLR|C_WS_PIC_DRAW,IM_BUTTON_POP_01_M_08,INVALID_INDEX,INVALID_INDEX,INVALID_INDEX,    C_MIXER,    C_MIXER |0xF6,IM_BUTTON_POP_02_L,INVALID_INDEX, IM_BUTTON_POP_01_R_09,   INVALID_INDEX, LIB_ICON},
//WSTL_DIAG_WIN_8BIT
    {SD_CLR|C_WS_LINE_CIRCL_DRAW,0xEF,0xEF,0xEF,0xEF,0x39,0xEF,INVALID_INDEX,INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX},
//WSTL_DIAG_BUTTON_01_8BIT
    {SD_CLR|C_WS_LINE_DRAW,C_NOSHOW,C_NOSHOW,C_NOSHOW,C_NOSHOW,0x39,0xEF,INVALID_INDEX,INVALID_INDEX, INVALID_INDEX,   INVALID_INDEX, INVALID_INDEX},

//WSTL_DSK_CON
    {SD_CLR|C_WS_LINE_DRAW,  C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0xF2 , C_MIXER | 0xF5, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_VOL_CON
    {SD_CLR|C_WS_LINE_DRAW,  0xF4, 0xF4, 0xF4, 0xF4, 0xF2 , C_MIXER | 0xF5, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_VOL_CON_HL
    {SD_CLR|C_WS_LINE_DRAW,  0x2A, 0x2A, 0x2A, 0x2A, 0xA1 , C_MIXER | 0xF5, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_NONVOL_CON
    {SD_CLR|C_WS_LINE_DRAW,  0xF4, 0xF4, 0xF4, 0xF4, 0xF7 , C_MIXER | 0xF5, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_NONVOL_CON_HL
    {SD_CLR|C_WS_LINE_DRAW,  0x2A, 0x2A, 0x2A, 0x2A, 0x45 , C_MIXER | 0xF5, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_VOL_TXT
    {SD_CLR|C_WS_LINE_DRAW,  C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, 0xDA , C_MIXER | 0xF5, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
//WSTL_DISK_TITLE
    {SD_CLR|C_WS_LINE_DRAW,  C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW, C_NOSHOW , C_MIXER | 0xF5, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
/* Noshow,Gray background,white foregound */ 
#ifdef FONT_1BIT_SUPPORT
    {SD_CLR|C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW,    C_NOSHOW,   C_NOSHOW, 0xB1 | C_MIX_BG, C_MIXER | 0xF4, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
#else
    {SD_CLR|C_WS_LINE_DRAW, C_NOSHOW, C_NOSHOW,    C_NOSHOW,   C_NOSHOW, C_NOSHOW | C_MIXER, C_MIXER | 0xF4, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX, INVALID_INDEX},
#endif
};

#define    SIZE_WINSTYLE    sizeof(w_shstyle1)/sizeof(WINSTYLE)

