/*****************************************************************************
*    Copyright (c) 2013 ALi Corp. All Rights Reserved
*    This source is confidential and is ALi's proprietary information.
*    This source is subject to ALi License Agreement, and shall not be
     disclosed to unauthorized individual.
*    File: cec_common_str.c
*
* Description:
*     Provide common string for HDMI CEC test.
*    THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
      KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
      IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
      PARTICULAR PURPOSE.
*****************************************************************************/

#include "cec_private.h"
#include "cec_common_str.h"

#ifdef    LIB_CEC_DEBUG

UINT8 *cec_opcode_str[] =
{
    // 0x00
    "Feature Abort(0x00)",
    "(0x01)",
    "(0x02)",
    "(0x03)",
    "Image View On(0x04)",
    "Tuner Step Increment(0x05)",
    "Tuner Step Decrement(0x06)",
    "Tuner Device Status(0x07)",
    "Give Tuner Device Status(0x08)",
    "Record On(0x09)",
    "Record Status(0x0A)",
    "Record Off(0x0B)",
    "(0x0C)",
    "Text View On(0x0D)",
    "(0x0E)",
    "Record TV Screen(0x0F)",

    // 0x10
    "(0x10)",
    "(0x11)",
    "(0x12)",
    "(0x13)",
    "(0x14)",
    "(0x15)",
    "(0x16)",
    "(0x17)",
    "(0x18)",
    "(0x19)",
    "Give Deck Status(0x1A)",
    "Deck Status(0x1B)",
    "(0x1C)",
    "(0x1D)",
    "(0x1E)",
    "(0x1F)",

    // 0x20
    "(0x20)",
    "(0x21)",
    "(0x22)",
    "(0x23)",
    "(0x24)",
    "(0x25)",
    "(0x26)",
    "(0x27)",
    "(0x28)",
    "(0x29)",
    "(0x2A)",
    "(0x2B)",
    "(0x2C)",
    "(0x2D)",
    "(0x2E)",
    "(0x2F)",

    // 0x30
    "(0x30)",
    "(0x31)",
    "Set Menu Language(0x32)",
    "Clear Analogue Timer(0x33)",
    "Set Analogte Timer(0x34)",
    "Timer Status(0x35)",
    "System Standby(0x36)",
    "(0x37)",
    "(0x38)",
    "(0x39)",
    "(0x3A)",
    "(0x3B)",
    "(0x3C)",
    "(0x3D)",
    "(0x3E)",
    "(0x3F)",

    // 0x40
    "(0x40)",
    "Play(0x41)",
    "Deck Control(0x42)",
    "Timer Clear Status(0x43)",
    "User Control Pressed(0x44)",
    "User Control Released(0x45)",
    "Give OSD Name(0x46)",
    "Set OSD Name(0x47)",
    "(0x48)",
    "(0x49)",
    "(0x4A)",
    "(0x4B)",
    "(0x4C)",
    "(0x4D)",
    "(0x4E)",
    "(0x4F)",

    // 0x50
    "(0x50)",
    "(0x51)",
    "(0x52)",
    "(0x53)",
    "(0x54)",
    "(0x55)",
    "(0x56)",
    "(0x57)",
    "(0x58)",
    "(0x59)",
    "(0x5A)",
    "(0x5B)",
    "(0x5C)",
    "(0x5D)",
    "(0x5E)",
    "(0x5F)",

    // 0x60
    "(0x60)",
    "(0x61)",
    "(0x62)",
    "(0x63)",
    "Set OSD String(0x64)",
    "(0x65)",
    "(0x66)",
    "Set Timer Program Title(0x67)",
    "(0x68)",
    "(0x69)",
    "(0x6A)",
    "(0x6B)",
    "(0x6C)",
    "(0x6D)",
    "(0x6E)",
    "(0x6F)",

    // 0x70
    "System Audio Mode Request(0x70)",
    "Give Audio Status(0x71)",
    "Set System Audio Mode(0x72)",
    "(0x73)",
    "(0x74)",
    "(0x75)",
    "(0x76)",
    "(0x77)",
    "(0x78)",
    "(0x79)",
    "Report Audio Status(0x7A)",
    "(0x7B)",
    "(0x7C)",
    "Give System Audio Mode Status(0x7D)",
    "System Audio Mode Status(0x7E)",
    "(0x7F)",

    // 0x80
    "Routing Change(0x80)",
    "Routing Information(0x81)",
    "Active Source(0x82)",
    "Give Physical Address(0x83)",
    "Report Physical Address(0x84)",
    "Request Active Source(0x85)",
    "Set Stream Path(0x86)",
    "Device Vendor ID(0x87)",
    "(0x88)",
    "Vendor Command(0x89)",
    "Vendor Remote Button Down(0x8A)",
    "Vendor Remote Button Up(0x8B)",
    "Give Device Vendor ID(0x8C)",
    "Menu Request(0x8D)",
    "Menu Status(0x8E)",
    "Give Device Power Status(0x8F)",

    // 0x90
    "Report Power Status(0x90)",
    "Get Menu Language(0x91)",
    "Select Analogue Service(0x92)",
    "Select Digital Service(0x93)",
    "(0x94)",
    "(0x95)",
    "(0x96)",
    "Set Digital Timer(0x97)",
    "(0x98)",
    "Clear Digital Timer(0x99)",
    "Set Audio Rate(0x9A)",
    "(0x9B)",
    "(0x9C)",
    "Inactive Source(0x9D)",
    "CEC Version(0x9E)",
    "Get CEC Version(0x9F)",

    // 0xA0
    "Vendor Command With ID(0xA0)",
    "Clear External Timer(0xA1)",
    "Set External Timer(0xA2)",
    "Report Short Audio Descriptor(0xA3)",
    "Request Short Audio Descriptor(0xA4)",
    "(0xA5)",
    "(0xA6)",
    "(0xA7)",
    "(0xA8)",
    "(0xA9)",
    "(0xAA)",
    "(0xAB)",
    "(0xAC)",
    "(0xAD)",
    "(0xAE)",
    "(0xAF)",

    // 0xB0
    "(0xB0)",
    "(0xB1)",
    "(0xB2)",
    "(0xB3)",
    "(0xB4)",
    "(0xB5)",
    "(0xB6)",
    "(0xB7)",
    "(0xB8)",
    "(0xB9)",
    "(0xBA)",
    "(0xBB)",
    "(0xBC)",
    "(0xBD)",
    "(0xBE)",
    "(0xBF)",

    // 0xC0
    "(0xC0)",
    "(0xC1)",
    "(0xC2)",
    "(0xC3)",
    "(0xC4)",
    "(0xC5)",
    "(0xC6)",
    "(0xC7)",
    "(0xC8)",
    "(0xC9)",
    "(0xCA)",
    "(0xCB)",
    "(0xCC)",
    "(0xCD)",
    "(0xCE)",
    "(0xCF)",

    // 0xD0
    "(0xD0)",
    "(0xD1)",
    "(0xD2)",
    "(0xD3)",
    "(0xD4)",
    "(0xD5)",
    "(0xD6)",
    "(0xD7)",
    "(0xD8)",
    "(0xD9)",
    "(0xDA)",
    "(0xDB)",
    "(0xDC)",
    "(0xDD)",
    "(0xDE)",
    "(0xDF)",

    // 0xE0
    "(0xE0)",
    "(0xE1)",
    "(0xE2)",
    "(0xE3)",
    "(0xE4)",
    "(0xE5)",
    "(0xE6)",
    "(0xE7)",
    "(0xE8)",
    "(0xE9)",
    "(0xEA)",
    "(0xEB)",
    "(0xEC)",
    "(0xED)",
    "(0xEE)",
    "(0xEF)",

    // 0xF0
    "(0xF0)",
    "(0xF1)",
    "(0xF2)",
    "(0xF3)",
    "(0xF4)",
    "(0xF5)",
    "(0xF6)",
    "(0xF7)",
    "CDC Message(0xF8)",
    "(0xF9)",
    "(0xFA)",
    "(0xFB)",
    "(0xFC)",
    "(0xFD)",
    "(0xFE)",
    "Abort(0xFF)",
};

UINT8 *cdc_opcode_str[] =
{
    // 0x00
    "CDC_HEC_InquireState(0x00)",
    "CDC_HEC_ReportState(0x01)",
    "CDC_HEC_SetStateAdjacent(0x02)",
    "CDC_HEC_SetState(0x03)",
    "CDC_HEC_RequestDeactivation(0x04)",
    "CDC_HEC_NotifyAlive(0x05)",
    "CDC_HEC_Discover(0x06)",
    "(0x07)",
    "(0x08)",
    "(0x09)",
    "(0x0A)",
    "(0x0B)",
    "(0x0C)",
    "(0x0D)",
    "(0x0E)",
    "(0x0F)",

    // 0x10
    "CDC_HPD_SetState(0x10)",
    "CDC_HPD_ReportState(0x11)",
};

UINT8 *cec_key_str[] =
{
    // 0x00
    "CEC_KEY_SELECT",
    "CEC_KEY_UP",
    "CEC_KEY_DOWN",
    "CEC_KEY_LEFT",
    "CEC_KEY_RIGHT",
    "CEC_KEY_RIGHT_UP",
    "CEC_KEY_RIGHT_DOWN",
    "CEC_KEY_LEFT_UP",
    "CEC_KEY_LEFT_DOWN",
    "CEC_KEY_ROOT_MENU",
    "CEC_KEY_SETUP_MENU",
    "CEC_KEY_CONTENT_MENU",
    "CEC_KEY_FAVORITE_MENU",
    "CEC_KEY_EXIT",
    "(0x0E)",
    "(0x0F)",

    // 0x10
    "CEC_KEY_MEDIA_TOP_MENU",
    "CEC_KEY_MEDIA_CONTEXT",
    "(0x12)",
    "(0x13)",
    "(0x14)",
    "(0x15)",
    "(0x16)",
    "(0x17)",
    "(0x18)",
    "(0x19)",
    "(0x1A)",
    "(0x1B)",
    "(0x1C)",
    "CEC_KEY_NUMBER_ENTRY_MODE",
    "CEC_KEY_NUM_11",
    "CEC_KEY_NUM_12",

    // 0x20
    "CEC_KEY_NUM_0",
    "CEC_KEY_NUM_1",
    "CEC_KEY_NUM_2",
    "CEC_KEY_NUM_3",
    "CEC_KEY_NUM_4",
    "CEC_KEY_NUM_5",
    "CEC_KEY_NUM_6",
    "CEC_KEY_NUM_7",
    "CEC_KEY_NUM_8",
    "CEC_KEY_NUM_9",
    "CEC_KEY_DOT",
    "CEC_KEY_ENTER",
    "CEC_KEY_CLEAR",
    "(0x2D)",
    "(0x2E)",
    "CEC_KEY_NEXT_FAVORITE",

    // 0x30
    "CEC_KEY_CHANNEL_UP",
    "CEC_KEY_CHANNEL_DOWN",
    "CEC_KEY_PREVIOUS_CHANNEL",
    "CEC_KEY_SOUND_SELECT",
    "CEC_KEY_INPUT_SELECT",
    "CEC_KEY_DISPLAY_INFORMATION",
    "CEC_KEY_HELP",
    "CEC_KEY_PAGE_UP",
    "CEC_KEY_PAGE_DOWN",
    "(0x39)",
    "(0x3A)",
    "(0x3B)",
    "(0x3C)",
    "(0x3D)",
    "(0x3E)",
    "(0x3F)",

    // 0x40
    "CEC_KEY_POWER",
    "CEC_KEY_VOLUME_UP",
    "CEC_KEY_VOLUME_DOWN",
    "CEC_KEY_MUTE",
    "CEC_KEY_PLAY",
    "CEC_KEY_STOP",
    "CEC_KEY_PAUSE",
    "CEC_KEY_RECORD",
    "CEC_KEY_REWIND",
    "CEC_KEY_FAST_FORWARD",
    "CEC_KEY_EJECT",
    "CEC_KEY_FORWARD",
    "CEC_KEY_BACKWARD",
    "CEC_KEY_STOP_RECORD",
    "CEC_KEY_PAUSE_RECORD",
    "(0x4F)",

    // 0x50
    "CEC_KEY_ANGLE",
    "CEC_KEY_SUB_PICTURE",
    "CEC_KEY_VIDEO_ON_DEMAND",
    "CEC_KEY_EPG",
    "CEC_KEY_TIMER_PROGRAMMING",
    "CEC_KEY_INITIAL_CONFIGURATION",
    "CEC_KEY_SELECT_BROADCAST_TYPE",
    "CEC_KEY_SELECT_SOUND_PRESENTATION",
    "(0x58)",
    "(0x59)",
    "(0x5A)",
    "(0x5B)",
    "(0x5C)",
    "(0x5D)",
    "(0x5E)",
    "(0x5F)",

    // 0x60
    "CEC_KEY_PLAY_FUNCTION",
    "CEC_KEY_PAUSE_PLAY_FUNCTION",
    "CEC_KEY_RECORD_FUNCTION",
    "CEC_KEY_PAUSE_RECORD_FUNCTION",
    "CEC_KEY_STOP_FUNCTION",
    "CEC_KEY_MUTE_FUNCTION",
    "CEC_KEY_RESTORE_VOLUME_FUNCTION",
    "CEC_KEY_TUNE_FUNCTION",
    "CEC_KEY_SELECT_MEDIA_FUNCTION",
    "CEC_KEY_SELECT_AV_INPUT_FUNCTION",
    "CEC_KEY_SELECT_AUDIO_INPUT_FUNCTION",
    "CEC_KEY_POWER_TOGGLE_FUNCTION",
    "CEC_KEY_POWER_OFF_FUNCTION",
    "CEC_KEY_POWER_ON_FUNCTION",
    "(0x6E)",
    "(0x6F)",

    // 0x70
    "(0x70)",
    "CEC_KEY_BLUE",
    "CEC_KEY_RED",
    "CEC_KEY_GREEN",
    "CEC_KEY_YELLOW",
    "CEC_KEY_F5",
    "CEC_KEY_DATA",
    "(0x77)",
    "(0x78)",
    "(0x79)",
    "(0x7A)",
    "(0x7B)",
    "(0x7C)",
    "(0x7D)",
    "(0x7E)",
    "(0x7F)",

    // 0x80
    "(0x80)",
    "(0x81)",
    "(0x82)",
    "(0x83)",
    "(0x84)",
    "(0x85)",
    "(0x86)",
    "(0x87)",
    "(0x88)",
    "(0x89)",
    "(0x8A)",
    "(0x8B)",
    "(0x8C)",
    "(0x8D)",
    "(0x8E)",
    "(0x8F)",

    // 0x90
    "(0x90)",
    "(0x91)",
    "(0x92)",
    "(0x93)",
    "(0x94)",
    "(0x95)",
    "(0x96)",
    "(0x97)",
    "(0x98)",
    "(0x99)",
    "(0x9A)",
    "(0x9B)",
    "(0x9C)",
    "(0x9D)",
    "(0x9E)",
    "(0x9F)",

    // 0xA0
    "(0xA0)",
    "(0xA1)",
    "(0xA2)",
    "(0xA3)",
    "(0xA4)",
    "(0xA5)",
    "(0xA6)",
    "(0xA7)",
    "(0xA8)",
    "(0xA9)",
    "(0xAA)",
    "(0xAB)",
    "(0xAC)",
    "(0xAD)",
    "(0xAE)",
    "(0xAF)",

    // 0xB0
    "(0xB0)",
    "(0xB1)",
    "(0xB2)",
    "(0xB3)",
    "(0xB4)",
    "(0xB5)",
    "(0xB6)",
    "(0xB7)",
    "(0xB8)",
    "(0xB9)",
    "(0xBA)",
    "(0xBB)",
    "(0xBC)",
    "(0xBD)",
    "(0xBE)",
    "(0xBF)",

    // 0xC0
    "(0xC0)",
    "(0xC1)",
    "(0xC2)",
    "(0xC3)",
    "(0xC4)",
    "(0xC5)",
    "(0xC6)",
    "(0xC7)",
    "(0xC8)",
    "(0xC9)",
    "(0xCA)",
    "(0xCB)",
    "(0xCC)",
    "(0xCD)",
    "(0xCE)",
    "(0xCF)",

    // 0xD0
    "(0xD0)",
    "(0xD1)",
    "(0xD2)",
    "(0xD3)",
    "(0xD4)",
    "(0xD5)",
    "(0xD6)",
    "(0xD7)",
    "(0xD8)",
    "(0xD9)",
    "(0xDA)",
    "(0xDB)",
    "(0xDC)",
    "(0xDD)",
    "(0xDE)",
    "(0xDF)",

    // 0xE0
    "(0xE0)",
    "(0xE1)",
    "(0xE2)",
    "(0xE3)",
    "(0xE4)",
    "(0xE5)",
    "(0xE6)",
    "(0xE7)",
    "(0xE8)",
    "(0xE9)",
    "(0xEA)",
    "(0xEB)",
    "(0xEC)",
    "(0xED)",
    "(0xEE)",
    "(0xEF)",

    // 0xF0
    "(0xF0)",
    "(0xF1)",
    "(0xF2)",
    "(0xF3)",
    "(0xF4)",
    "(0xF5)",
    "(0xF6)",
    "(0xF7)",
    "(0xF8)",
    "(0xF9)",
    "(0xFA)",
    "(0xFB)",
    "(0xFC)",
    "(0xFD)",
    "(0xFE)",
    "(0xFF)",
};

UINT8 *cec_short_audio_desc_str[] =
{
    "RESERVED(0x0)",
    "LPCM(0x1)",
    "AC3(0x2)",
    "MPEG1(0x3)",
    "MP3(0x4)",
    "MPEG2(0x5)",
    "AAC(0x6)",
    "DTS(0x7)",
    "ATRAC(0x8)",
    "ONE_BIT_AUDIO(0x9)",
    "DD+(0xA)",
    "DTS_HD(0xB)",
    "MAT(0xC)",
    "DST(0xD)",
    "BYE1_PRO(0xE)",
    "RESERVED(0xF)",
};

#endif

