/*****************************************************************************
*    Copyright (c) 2013 ALi Corp. All Rights Reserved
*    This source is confidential and is ALi's proprietary information.
*    This source is subject to ALi License Agreement, and shall not be
     disclosed to unauthorized individual.
*    File: osd_config.h
*
*    Description: osd winstyle config.
*    THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
*      KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
*      IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
*      PARTICULAR PURPOSE.
*****************************************************************************/
#ifndef    _OSDCONFIG_H_
#define    _OSDCONFIG_H_
#ifdef __cplusplus
extern "C"
{
#endif
// Color Definition
// It must co-work with pallette board

typedef enum
{
    WSTL_NOSHOW_IDX = 0,
    WSTL_TRANS_IX,
    WSTL_MIXBACK_BLACK_IDX,
    WSTL_MIXBACK_WHITE_IDX,
    WSTL_WIN_TITLE_01_HD,
    WSTL_WIN_BODYRIGHT_01_HD,
    WSTL_WIN_BODYLEFT_01_HD,
    WSTL_WIN_MAINMENU_01_HD,
    WSTL_WIN_MAINMENU_01_BG_HD,
    WSTL_WINCHANNELIST_01_HD,
    WSTL_VOLUME_01_HD,
    WSTL_VOLUME_01_BG_HD,
    WSTL_VOLUME_01_FG_HD,
    WSTL_VOLUME_02_FG,
    WSTL_AUDIO_WIN_01,
    WSTL_POP_WIN_01_HD,

    WSTL_WINCHANNELIST_TEXT_T,
    WSTL_WINCHANNELIST_TEXT_M,
    WSTL_WINCHANNELIST_TEXT_B,
    WSTL_WINSEARCH,
    WSTL_WINSEARCH_01_HD,
    WSTL_WINSEARCH_02_HD,
    WSTL_WINSEARCH_03_HD,
    WSTL_ZOOM_WIN_01_RECT,
    WSTL_KEYBOARD_01_HD,
    WSTL_SCROLLBAR_01_HD,
    WSTL_SCROLLBAR_02_HD,
    WSTL_BUTTON_01_HD,
    WSTL_BUTTON_01_FG_HD,
    WSTL_BUTTON_02_HD,
    WSTL_BUTTON_02_FG_HD,
    WSTL_BUTTON_03_HD,
    WSTL_BUTTON_03_FG_HD,
    WSTL_BUTTON_04_HD,
    WSTL_BUTTON_05_HD,//40
    WSTL_BUTTON_07_HD,
    WSTL_BUTTON_08_HD,                                //36
//    WSTL_BUTTON_10,
//    WSTL_BUTTON_11_HD,
    WSTL_KEYBOARDBUTTON_01_SH_HD,
    WSTL_KEYBOARDBUTTON_01_HL_HD,
    WSTL_KEYBOARDBUTTON_02_SH_HD,
    WSTL_KEYBOARDBUTTON_02_HL_HD,
    WSTYL_COLBTN_RED,
    WSTYL_COLBTN_RED_SELECT,
    WSTYL_COLBTN_GREEN,
    WSTYL_COLBTN_GREEN_SELECT,//60
    WSTYL_COLBTN_YELLOW,
    WSTYL_COLBTN_YELLOW_SELECT,
    WSTYL_COLBTN_BLUE,
    WSTYL_COLBTN_BLUE_SELECT,
    WSTYL_COLBTN_GRAY,
    WSTYL_COLBTN_GRAY_SELECT,
    WSTL_BUTTON_POP_SH_HD,
    WSTL_BUTTON_POP_HL_HD,
    WSTL_BUTTON_SHOR_HD,
    WSTL_BUTTON_SHOR_HI_HD,
    WSTL_BUTTON_SHOR_GRY_HD,
    WSTL_BARBG_01,
    WSTL_BAR_06,
    WSTL_TEXT_04_HD,
    WSTL_TEXT_08_HD,
    WSTL_TEXT_09_HD,
    WSTL_TEXT_10_HD,
    WSTL_TEXT_11_HD,
//    WSTL_TEXT_13_HD,
    WSTL_TEXT_TRANS_11_HD,
    WSTL_TEXT_13,
    WSTL_TEXT_14,
    WSTL_TEXT_20_HD,
    WSTL_TEXT_25,
    WSTL_TEXT_26,
    WSTL_GAMEWIN_01_HD,
    WSTL_GAMESUDOKU_NORMAL1_HD,
    WSTL_GAMESUDOKU_NORMAL2_HD,
    WSTL_GAMESUDOKU_FIX_HD,
    WSTL_GAMESUDOKU_CURSOR_HD,//120
    WSTL_TEXT_07,
    WSTL_TEXT_06,
    WSTL_MP_PREV_01,
    WSTL_MP_PREV_02,
//77
    WSTL_MIXBACK_BLACK_IDX_HD,
    WSTL_MIXBACK_WHITE_IDX_HD,//140
    WSTL_LINE_HD,
    WSTL_LINE_MENU_HD,
    WSTL_TEXT_01_HD,
    WSTL_TEXT_02_HD,
    WSTL_TEXT_03_HD,
    WSTL_TEXT_05_HD,
    WSTL_TEXT_06_HD,
    WSTL_TEXT_07_HD,
    WSTL_TEXT_12_HD,
    WSTL_TEXT_21_HD,
    WSTL_TEXT_22_HD,
    WSTL_TEXT_23_HD,
    WSTL_TEXT_24_HD,
    WSTL_TEXT_25_HD,
    WSTL_TEXT_26_HD,
    WSTL_TEXT_27_HD,
    WSTL_TEXT_28_HD,
    WSTL_WIN_EPG_LINE_01_HD,
    WSTL_WIN_EPG_01_HD,
    WSTL_WIN_EPG_02_HD,
    WSTL_WIN_EPG_HELP_HD,//100
    WSTL_BARBG_01_HD,
    WSTL_BAR_01_HD,
    WSTL_BAR_02_HD,
    WSTL_BAR_03_HD,
    WSTL_BAR_04_HD,
    WSTL_MIX_BMP_HD,
    WSTL_POP_MIX_BMP_HD,
    WSTL_POP_TXT_SH_HD,
    WSTL_POP_TXT_TITLE_HD,
    WSTL_POP_TXT_SH_01_HD,
    WSTL_PREV_01_HD,
    WSTL_MP3_BAR01_HD,
    WSTL_POP_LINE_HD,
    WSTL_BUTTON_SELECT_HD,
    WSTL_MP_WIN_MIDDLE_HD,
    WSTL_MP_WIN_BOTTOM_HD,
    WSTL_MP_HELP_HD,
    WSTL_MP_BUTTON_02_HD,
    WSTL_MP_BARBG_01_HD,
    WSTL_MP_PREV_01_HD,//140
    WSTL_MP_PREV_02_HD,
    WSTL_MP_DEV_SH_HD,
    WSTL_MP_DEV_HL_HD,
    WSTL_MP_DEV_TXT_HD,
    WSTL_MP_SPCTRM_GRAY_HD,
    WSTL_MP_SPCTRM_BAR_HD,
    WSTL_CHAN_PREVIEW_INPUT_HD,
    WSTL_MP_DIR_HD,
    WSTL_MP_DIR_TXT_HD,
    WSTL_MP_MUTE_BG_HD,
    WSTL_MP_POP_WIN_01_HD,
    WSTL_MP_HELP_GRY,

    WSTL_INFO_01_8BIT,
    WSTL_MIXBACK_IDX_8BIT,
    WSTL_MIXBACK_IDX_01_8BIT,
    WSTL_MIXBACK_IDX_02_8BIT,
    WSTL_MIXBACK_IDX_03_8BIT,
    WSTL_MIXBACK_IDX_04_8BIT,
    WSTL_MIXBACK_IDX_05_8BIT,//160
    WSTL_MIXBACK_IDX_06_8BIT,
    WSTL_MIXBACK_IDX_07_8BIT,
    WSTL_INFO_CHINPUT_01_8BIT,
    WSTL_VOLUME_01_8BIT,
    WSTL_VOLUME_01_BG_8BIT,
    WSTL_VOLUME_01_FG_8BIT,
    WSTL_POP_WIN_01_8BIT,
    WSTL_TEXT_04_8BIT,
    WSTL_KEYBOARD_01_8BIT,
    WSTL_KEYBOARDBUTTON_01_SH_8BIT,
    WSTL_KEYBOARDBUTTON_01_HL_8BIT,
    WSTL_KEYBOARDBUTTON_02_SH_8BIT,//170
    WSTL_KEYBOARDBUTTON_02_HL_8BIT,
    WSTL_WIN_SLIST_01_8BIT,
    WSTL_WIN_SLIST_02_8BIT,
    WSTL_TEXT_16_8BIT,
    WSTL_BUTTON_05_8BIT,
    WSTL_TEXT_15_8BIT,
    WSTL_TEXT_01_8BIT,
    WSTL_TEXT_28_8BIT,
    WSTL_TEXT_29_8BIT,
    WSTL_TEXT_30_8BIT,//180
    WSTL_SCROLLBAR_01_8BIT,
    WSTL_SCROLLBAR_02_8BIT,
    WSTL_POP_WIN_02_8BIT,//164
//    WSTL_POP_LINE_8BIT,
//    WSTL_MAINMENU_LINE_8BIT,
    WSTL_BARBG_01_8BIT,
    WSTL_BAR_01_8BIT,
    WSTL_BAR_02_8BIT,
    WSTL_BAR_03_8BIT,
    WSTL_BAR_04_8BIT,
    WSTL_POP_TEXT_8BIT,
#if defined( SUPPORT_CAS9) || defined( SUPPORT_CAS7)
    WSTL_POP_TEXT_16BIT,
#endif
    WSTL_BUTTON_POP_SH_8BIT,
    WSTL_BUTTON_POP_HL_8BIT,
    WSTL_DIAG_WIN_8BIT,
    WSTL_DIAG_BUTTON_01_8BIT,
//    WSTL_ZOOM_WIN_8BIT,

    WSTL_DSK_CON,
    WSTL_VOL_CON,
    WSTL_VOL_CON_HL,
    WSTL_NONVOL_CON,
    WSTL_NONVOL_CON_HL,
    WSTL_VOL_TXT,
    WSTL_DISK_TITLE,
#ifdef SUPPORT_CAS_A
    WSTL_TEXT_29_HD,
#endif
    WSTL_MIXBACK_IDX_08_8BIT,
#if defined(SUPPORT_BC_STD) ||    defined(SUPPORT_BC)
    WSTL_BC_MESSAGE_BOX,
    WSTL_OSM_POP_UP_TEXT_FG_BLACK,
#endif
#ifdef CAS9_V6 //mailbox_read
    WSTL_CNX_MAILLIST_HAVE_READ,
#endif
//182
//32bit UI ,winstyle define from here
	WSTL_N_MAINMENU_CON1,
	WSTL_N_MM_SEL,
	WSTL_N_LM_SEL,
	WSTL_N_LM_UNSEL,
	WSTL_N_TXT1,
	WSTL_N_TXT2,
	WSTL_N_TXT3,
	WSTL_N_PREVIEW,	
//win2_search.xform style
	WSTL_N_SIGNAL_BG,
	WSTL_N_SIGNAL_FG,
	
	WSTL_N_PROGRESS_BG,
	WSTL_N_SEARCH_BG,
	WSTL_N_SRCH_TVTITLE,
       WSTL_N_TVRADIO_UNSEL,

//public winstyle
       WSTL_N_PRSCRN1,
       WSTL_N_PRSCRN2,
       WSTL_N_PRSCRN3,
//       WSTL_N_PRSCRN4,
       WSTL_N_PRSCRN5,
       WSTL_N_PRSCRN6,
       
//win2_fullsearch.xform style
       WSTL_N_LEFT_BUTTON,
       WSTL_N_RIGHT_BUTTON,

//win2_parental_guidance.xform
       WSTL_N_PWDIALOG_SEL,
       WSTL_N_PWDIALOG_UNSEL,
       WSTL_N_TXT5,

//win2_epg.xform style
       WSTL_N_EPG_SEL,
       WSTL_N_EPG_SEL_RT,
	WSTL_N_WEEKDAY_BG,
	WSTL_N_WEEKDAY_ITEM,
	WSTL_N_WEEKDAY_SEL,

//win2_reserve_manage.xform style
      	WSTL_N_TIMER_SEL,
	WSTL_N_TIMER_TITLE,
//test
       WSTL_N_TXT6,

//win2_prog_name.xform style
	WSTL_N_PROGNAME_TITLE,

//win2_volume.xform style
      	WSTL_N_VOLUMEBAR_BG,
	WSTL_N_VOLUMEBAR_FG,

//win_com_popup.c style
       WSTL_N_POPUP_BG,
       WSTL_N_POPUP_TITLE,
       WSTL_N_POPUP_MULTXT,
       WSTL_N_POPUP_BUTTON_SEL,
       WSTL_N_POPUP_BUTTON_UNSEL,

//win2_prog_info.xform style
       WSTL_N_PROGINFO_SH,

//win_prog_light_list.c style
	WSTL_N_LIST_UNSEL,
       WSTL_N_LIST_SEL,

//win_chan_list.c style
       WSTL_N_CHAN_PREVIEW_INPUT_HD,
       WSTL_N_COMLIST_TITLE,
	WSTL_N_COMLIST_BG,
	WSTL_N_COMLIST_SEL_ITEM,

//win2_mainmenu.xform
	WSTL_N_MM_SELECTED,
	WSTL_N_LM_SELECTED,

//win2_favlist.xform
       WSTL_N_FAV_BG,
	WSTL_N_FAVLIST_LINE,

//win2_usb_filelist.xform
        WSTL_PVR_ITEMSEL,
        WSTL_PLAYLIST_PROGRESS_BG,
        WSTL_PLAYLIST_TICK_BG,
        WSTL_PLAYLIST_TICK_FG,

//ca menu
	WSTL_N_BULU0_BG,
	WSTL_N_BULU1_BG,
	WSTL_N_BULU2_BG,
	WSTL_N_BULU3_BG,
	WSTL_N_BULU4_BG,
	WSTL_N_BULU1_BG_CIRCL,
	WSTL_N_BULU2_BG_CIRCL,
	WSTL_N_BULU2_BUTTON_SEL,
	WSTL_N_BULU2_BUTTON_UNSEL,
	WSTL_N_POPUP_SEL
}winstle_id_t;

#ifdef __cplusplus
}
#endif
#endif


