#include "../../chip/m3711c/chip_m3711c.h"
#include "../board_cfg.h"
#include "tve_hd_setting_half_mode.h"
#include "tve_old_cfg_setting_m3606.h"
#include <sys_config.h>
#include <hld/nim/nim_tuner.h>
#include <hld/nim/nim.h>
#include <bus/i2c/i2c.h>
//====================================================================================//
//#define SUPPORT_GOS_IR_G006
#define M3100_REV_ID (4)
#define SYS_BOARD_IS_M3606_01V02
#define bitmap_list NULL
#define bitmap_list_num (0)
#define MEM_GPIO_ENABLED (0)
#define SYS_I2C_SDA2 (23)
#define SYS_I2C_SCL2 (24)
#define ALI_HW_REG_R32(i) (*(volatile unsigned int *)(i))
#define ALI_HW_REG_W32(i, d) do {(*(volatile unsigned int *)(i)) = (d);} while(0)
//====================================================================================//

#if (SYS_DEM_MODULE == COFDM_S3811)
extern INT32 nim_s3811_attach_ext(struct COFDM_TUNER_CONFIG_API *ptrCOFDM_Tuner);
#endif
extern INT32 nim_m3101_dev_attach_ext(char *name, PCOFDM_TUNER_CONFIG_API pConfig);
extern INT32 i2c_scb_write(UINT32 id, UINT8 slv_addr, UINT8 *data, int len);
extern INT32 i2c_scb_read(UINT32 id,UINT8 slv_addr, UINT8 *data, int len);
extern INT32 i2c_scb_write_read(UINT32 id, UINT8 slv_addr, UINT8 *data, int wlen, int rlen);
extern INT32 i2c_gpio_read(UINT32 id, UINT8 slv_addr, UINT8 *data, int len);
extern INT32 i2c_gpio_write(UINT32 id, UINT8 slv_addr, UINT8 *data, int len);
extern INT32 i2c_gpio_write_read(UINT32 id, UINT8 slv_addr, UINT8 *data, int wlen, int rlen);
extern INT32 tun_mxl5007_init_ISDBT_mode(UINT32 *tuner_id, struct COFDM_TUNER_CONFIG_EXT * ptrTuner_Config);
extern INT32 scart_mx9671_attach(struct scart_init_param * param);
//extern void pan_ch455_id_set(struct pan_device *dev, UINT32 id);
//extern INT32 pan_ch455_attach(struct pan_configuration *config);
extern INT32 pan_fd650_gp_attach(struct pan_configuration *config);
board_cfg board_config;

static const struct ir_key_map_t g_itou_key_tab[] =
{
	/*ali 60 key remote controller.*/
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df926d)}, V_KEY_0},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dfc837)}, V_KEY_1},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df08f7)}, V_KEY_2},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df8877)}, V_KEY_3},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dff00f)}, V_KEY_4},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df30cf)}, V_KEY_5},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dfb04f)}, V_KEY_6},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dfd02f)}, V_KEY_7},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df10ef)}, V_KEY_8},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df906f)}, V_KEY_9},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df38c7)}, V_KEY_LEFT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df12ed)}, V_KEY_RIGHT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df22dd)}, V_KEY_UP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dfb847)}, V_KEY_DOWN},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df50af)}, V_KEY_MP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df3ac5)}, V_KEY_ENTER},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dfd22d)}, V_KEY_P_UP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dfe01f)}, V_KEY_P_DOWN},
	//{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f28d7)}, V_KEY_BOOKMARK},
	//{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fa857)}, V_KEY_JUMPMARK},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df827d)}, V_KEY_TEXT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df708f)}, V_KEY_POWER},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df20df)}, V_KEY_PREV},//20
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df0af5)}, V_KEY_NEXT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df629d)}, V_KEY_AUDIO},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df807f)}, V_KEY_SUBTITLE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df9867)}, V_KEY_SLEEP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dfe21d)}, V_KEY_FIND},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dfa05f)}, V_KEY_MUTE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df7a85)}, V_KEY_PAUSE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dfa25d)}, V_KEY_VIDEO_FORMAT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df6897)}, V_KEY_INFOR},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df42bd)}, V_KEY_EXIT},//30
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df52ad)}, V_KEY_TVSAT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df02fd)}, V_KEY_TVRADIO},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dfc23d)}, V_KEY_FAV},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dfa857)}, V_KEY_RECORD},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df18e7)}, V_KEY_PLAY},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df58a7)}, V_KEY_FB},//red
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dfd827)}, V_KEY_FF},//green
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df4ab5)}, V_KEY_B_SLOW},//yellow
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dfaa55)}, V_KEY_SLOW},//blue
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dfe817)}, V_KEY_STOP},//40
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df40bf)}, V_KEY_ZOOM},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df00ff)}, V_KEY_EPG},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df2ad5)}, V_KEY_MENU},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dfc03f)}, V_KEY_RECALL},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df609f)}, V_KEY_RED},//red
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df7887)}, V_KEY_GREEN},//green
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dff807)}, V_KEY_YELLOW},//yellow
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dfba45)}, V_KEY_BLUE},//blue

	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dfca35)}, V_KEY_PVR_INFO},//49
#if((!defined SUPPORT_CAS9)|| (defined MEDIAPLAYER_SUPPORT))
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dfb24d)}, V_KEY_FILELIST},
#endif
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df8a75)}, V_KEY_DVRLIST},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df1ae5)}, V_KEY_USBREMOVE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df6a95)}, V_KEY_PIP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df9a65)}, V_KEY_PIP_LIST},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df5aa5)}, V_KEY_SWAP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dfda25)}, V_KEY_MOVE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60dfea15)}, V_KEY_REPEATAB},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df28d7)}, V_KEY_F_UP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x60df48b7)}, V_KEY_F_DOWN},


#if 0//new or change add by yuj
    // ali 48 key remote controller.
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fb24d)}, V_KEY_0},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f22dd)}, V_KEY_1},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fa25d)}, V_KEY_2},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f629d)}, V_KEY_3},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fe21d)}, V_KEY_4},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f12ed)}, V_KEY_5},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f926d)}, V_KEY_6},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f52ad)}, V_KEY_7},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fd22d)}, V_KEY_8},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f32cd)}, V_KEY_9},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f9867)}, V_KEY_LEFT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f58a7)}, V_KEY_RIGHT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f18e7)}, V_KEY_UP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fd827)}, V_KEY_DOWN},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f906f)}, V_KEY_MP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807ff20d)}, V_KEY_ENTER},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f28d7)}, V_KEY_P_UP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fa857)}, V_KEY_P_DOWN},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f28d7)}, V_KEY_BOOKMARK},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fa857)}, V_KEY_JUMPMARK},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fc837)}, V_KEY_TEXT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fc03f)}, V_KEY_POWER},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f6897)}, V_KEY_PREV},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fe817)}, V_KEY_NEXT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f40bf)}, V_KEY_AUDIO},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fd02f)}, V_KEY_TIMER},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f50af)}, V_KEY_SUBTITLE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fb04f)}, V_KEY_LIST},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807ff00f)}, V_KEY_SLEEP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f609f)}, V_KEY_FIND},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f30cf)}, V_KEY_MUTE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fb847)}, V_KEY_PAUSE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x00000156)}, V_KEY_SUBTITLE},
#ifdef HDTV_SUPPORT
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fa05f)}, V_KEY_VIDEO_FORMAT},
#else
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fa05f)}, V_KEY_HELP},
#endif
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f20df)}, V_KEY_INFOR},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f48b7)}, V_KEY_EXIT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f00ff)}, V_KEY_TVSAT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f807f)}, V_KEY_TVRADIO},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f10ef)}, V_KEY_FAV},
#ifdef DVR_PVR_SUPPORT
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f38c7)}, V_KEY_RECORD},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f7887)}, V_KEY_PLAY},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f02fd)}, V_KEY_FB},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f827d)}, V_KEY_FF},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f42bd)}, V_KEY_B_SLOW},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fc23d)}, V_KEY_SLOW},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807ff807)}, V_KEY_STOP},
#endif
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fe01f)}, V_KEY_LANGUAGE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f708f)}, V_KEY_ZOOM},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f08f7)}, V_KEY_EPG},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f8877)}, V_KEY_MENU},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f728d)}, V_KEY_RECALL},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f02fd)}, V_KEY_RED},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f827d)}, V_KEY_GREEN},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f42bd)}, V_KEY_YELLOW},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fc23d)}, V_KEY_BLUE},
 #else
 //ir_gos_3920_key_tab
 	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f08f7)},  		V_KEY_0},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f8877)},  		V_KEY_1},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f48b7)},  		V_KEY_2},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fc837)},  		V_KEY_3},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f28d7)},  		V_KEY_4},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fa857)},  		V_KEY_5},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f6897)},  		V_KEY_6},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fe817)},  		V_KEY_7},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f18e7)},  		V_KEY_8},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f9867)},  		V_KEY_9},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fc03f)},  		V_KEY_LEFT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f40bf)},  		V_KEY_RIGHT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f00ff)},  		V_KEY_UP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f807f)},  		V_KEY_DOWN},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f906f)},  		V_KEY_MP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807ff807)},  		V_KEY_ENTER},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fe01f)},  		V_KEY_INFOR},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fa05f)},  		V_KEY_FAV},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f2ad5)},  		V_KEY_TEXT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f50af)},    		V_KEY_POWER},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f6897)},  		V_KEY_PREV},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f20df)},  		V_KEY_AUDIO},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fd02f)},  		V_KEY_TIMER},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f0af5)},  		V_KEY_SUBTITLE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f30cf)},  		V_KEY_MUTE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f10ef)},   	 	V_KEY_PAUSE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f0af5)},  		V_KEY_SUBTITLE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fd827)},  		V_KEY_YELLOW},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f708f)},  		V_KEY_EXIT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f609f)},   		V_KEY_TVRADIO},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f827d)},   		V_KEY_RECALL},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f8a75)},  		V_KEY_RECORD},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f1ae5)},  		V_KEY_PLAY},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f32cd)},  		V_KEY_FB},//red
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f22dd)},  		V_KEY_FF},//green
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fc23d)},  		V_KEY_SLOW},//blue
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f3ac5)},  		V_KEY_STOP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807fb847)},   		V_KEY_EPG},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f02fd)},   		V_KEY_MENU},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807ff00f)},   		V_KEY_RED},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f906f)},  		V_KEY_GREEN},//red
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f38c7)},  		V_KEY_BLUE},//green
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f7887)},  		V_KEY_MAIL},//yellow
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x807f58a7)},  		V_KEY_LANGUAGE},//blue
//ir_gos_c008_key_tab
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x023448b7)},  		V_KEY_0},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x0234906f)},  		V_KEY_1},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x0234b847)},  		V_KEY_2},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x0234f807)},  		V_KEY_3},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x0234b04f)},  		V_KEY_4},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x02349867)},  		V_KEY_5},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x0234d827)},  		V_KEY_6},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x02348877)},  		V_KEY_7},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x0234a857)},  		V_KEY_8},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x0234e817)},  		V_KEY_9},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x0234708f)},  		V_KEY_LEFT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x023458a7)},  		V_KEY_RIGHT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x0234c03f)},  		V_KEY_UP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x023440bf)},  	 	V_KEY_DOWN},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x0234e01f)},  		V_KEY_ENTER},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x0234c837)},  		V_KEY_P_UP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x0234609f)},  		V_KEY_P_DOWN},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x0234ca35)},  		V_KEY_V_UP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x02344ab5)},  		V_KEY_V_DOWN},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x0234827d)},  		V_KEY_MUTE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x0234a25d)},    		V_KEY_POWER},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x023428d7)},   		V_KEY_MENU},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x0234ea15)},  		V_KEY_AUDIO},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x02346a95)},  		V_KEY_RECALL},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x0234f20d)},   	 	V_KEY_DATARADIO},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x02343ac5)},  		V_KEY_EXIT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x023418e7)},   		V_KEY_EPG},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x023438c7)},   		V_KEY_TVRADIO},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x023400ff)},  		V_KEY_RED},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x023430cf)},  		V_KEY_GREEN},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x023410ef)},  		V_KEY_YELLOW},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x023450af)},  		V_KEY_BLUE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x023400ff)},   		V_KEY_FAV},//red
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x023410ef)},  		V_KEY_BOOKMARK},//yellow
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x023408f7)},  		V_KEY_INFOR},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x0234926d)},  		V_KEY_FF},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x02348a75)},  		V_KEY_FF},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x0234728d)},  		V_KEY_FF},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x0234728d)},   		V_KEY_FF},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x02340af5)},   		V_KEY_FF},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x023412ed)},   		V_KEY_FF},

 #ifdef SUPPORT_GOS_IR_G006
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb48b7)}, V_KEY_0},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb906f)}, V_KEY_1},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebb847)}, V_KEY_2},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebf807)}, V_KEY_3},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebb04f)}, V_KEY_4},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb9867)}, V_KEY_5},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebd827)}, V_KEY_6},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb8877)}, V_KEY_7},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eba857)}, V_KEY_8},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebe817)}, V_KEY_9},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb708f)}, V_KEY_LEFT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb58a7)}, V_KEY_RIGHT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebc03f)}, V_KEY_UP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb40bf)}, V_KEY_DOWN},		
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebe01f)}, V_KEY_ENTER},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eba25d)}, V_KEY_POWER},
	
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb8a75)}, V_KEY_PREV},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb926d)}, V_KEY_NEXT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb4ab5)}, V_KEY_FB},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebca35)}, V_KEY_FF},

	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb52ad)}, V_KEY_PAUSE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb728d)}, V_KEY_STOP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb28d7)}, V_KEY_RECORD},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb28d7)}, V_KEY_PLAY},

	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebc837)}, V_KEY_SUBTITLE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0xffffffff)}, V_KEY_ASPECT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb609f)}, V_KEY_TEXT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb38c7)}, V_KEY_VIDEO_FORMAT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb00ff)}, V_KEY_DVRLIST},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb00ff)}, V_KEY_RED},
#ifdef BISS_HOT_KEY //SUPPORT_BISS
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x00ff1ae5)}, V_KEY_BISS},
#endif
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb10ef)}, V_KEY_GREEN},
#ifdef ENABLE_OTA
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0xffffffff)}, V_KEY_OTA},
#endif
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb50af)}, V_KEY_YELLOW},
	
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb30cf)}, V_KEY_AUDIO},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb30cf)}, V_KEY_BLUE},

	//{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0xffffffff)}, V_KEY_C_UP},	//V_KEY_C_UP
	//{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0xffffffff)}, V_KEY_C_DOWN},	//V_KEY_C_DOWN
	//{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0xffffffff)}, V_KEY_P_UP},	
	//{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0xffffffff)}, V_KEY_P_DOWN},	
	//{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0xffffffff)}, V_KEY_V_UP}, //V_KEY_V_UP	
	//{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0xffffffff)}, V_KEY_V_DOWN},

	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb12ed)}, V_KEY_EPG},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebf20d)}, V_KEY_MENU},
	//{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0xffffffff)}, V_KEY_SLEEP},
	//{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0xffffffff)}, V_KEY_FIND},

	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb18e7)}, V_KEY_FAV},
	//{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0xffffffff)}, V_KEY_SAT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb3ac5)}, V_KEY_EXIT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb6a95)}, V_KEY_EXIT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebea15)}, V_KEY_TVRADIO},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb08f7)}, V_KEY_INFOR},
	//{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0xffffffff)}, V_KEY_RECALL},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb827d)}, V_KEY_MUTE},
#else
//ir_gos_g003_key_tab
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb28d7)},  		V_KEY_0},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb58a7)},  		V_KEY_1},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb8877)},  		V_KEY_2},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb906f)},  		V_KEY_3},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebd827)},  		V_KEY_4},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb48b7)},  		V_KEY_5},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb50af)},  		V_KEY_6},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb38c7)},  		V_KEY_7},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebc837)},  		V_KEY_8},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebd02f)},  		V_KEY_9},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebe817)},  		V_KEY_LEFT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb6897)},  		V_KEY_RIGHT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebb04f)},  		V_KEY_UP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb7887)},  	 	V_KEY_DOWN},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebe01f)},  		V_KEY_ENTER},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb2ad5)},  		V_KEY_C_UP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb1ae5)},  		V_KEY_C_DOWN},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebaa55)},  		V_KEY_V_UP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb9a65)},  		V_KEY_V_DOWN},
	//{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb3ac5)},  		V_KEY_TEXT},
    	//{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb3ac5)},         V_KEY_MEDIA_APP},/*将V_KEY_TEXT丝印改为APP,为了便于应用兼容，修改V_KEY*/
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb18e7)},    		V_KEY_POWER},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb32cd)},  		V_KEY_PREV},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb926d)},  		V_KEY_NEXT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb06f9)},  		V_KEY_AUDIO},
	//{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb02fd)},  		V_KEY_SUBTITLE},
    //{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb02fd)},         V_KEY_GOTO}, /*将V_KEY_SUBTITLE丝印改为goto,为了便于应用兼容，修改V_KEY*/
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eba857)},  		V_KEY_MUTE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb708f)},   	 	V_KEY_PAUSE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eba05f)},  		V_KEY_VIDEO_FORMAT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb609f)},  		V_KEY_ASPECT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb30cf)},  		V_KEY_INFOR},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebf807)},  		V_KEY_EXIT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb807f)},   		V_KEY_TVRADIO},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb40bf)},   		V_KEY_FAV},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebba45)},  		V_KEY_RECORD},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebb24d)},  		V_KEY_PLAY},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb827d)},  		V_KEY_FB},//red
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eba25d)},  		V_KEY_FF},//green
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebf00f)},  		V_KEY_STOP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb8679)},  		V_KEY_DVRLIST},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb20df)},   		V_KEY_EPG},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb08f7)},   		V_KEY_MENU},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb00ff)},   		V_KEY_RECALL},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb9867)},  		V_KEY_RED},//red
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14eb10ef)},  		V_KEY_GREEN},//green
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebc03f)},  		V_KEY_YELLOW},//yellow
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x14ebb847)},  		V_KEY_BLUE},//blue
#endif
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bfe11e)}, V_KEY_0},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf49b6)}, V_KEY_1},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bfc936)}, V_KEY_2},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf33cc)}, V_KEY_3},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf718e)}, V_KEY_4},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bff10e)}, V_KEY_5},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf13ec)}, V_KEY_6},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf51ae)}, V_KEY_7},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bfd12e)}, V_KEY_8},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf23dc)}, V_KEY_9},		
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf9966)}, V_KEY_LEFT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf837c)}, V_KEY_RIGHT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf53ac)}, V_KEY_UP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf4bb4)}, V_KEY_DOWN},	

	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf8f70)}, V_KEY_AUDIO},
       {{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bfcf30)}, V_KEY_VIDEO_FORMAT},
       {{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf6f90)}, V_KEY_SUBTITLE},
       {{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf4fb0)}, V_KEY_TEXT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf2fd0)}, V_KEY_ASPECT},

       {{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bfa15e)}, V_KEY_C_UP},  //ch+
       {{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf619e)}, V_KEY_C_DOWN}, //ch-
       {{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf01fe)}, V_KEY_V_UP},  //vol+
       {{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf817e)}, V_KEY_V_DOWN}, //vol-
    
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf738c)}, V_KEY_ENTER},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80ba956)}, V_KEY_P_UP},        //page+
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bfbb44)}, V_KEY_P_DOWN},  //page-		
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf3bc4)}, V_KEY_POWER},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bfbb44)}, V_KEY_PREV},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80ba956)}, V_KEY_NEXT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf39c6)}, V_KEY_MUTE},
	//{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bfea15)}, V_KEY_PAUSE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf11ee)}, V_KEY_INFOR},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bfa35c)}, V_KEY_EXIT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bfc33c)}, V_KEY_TVRADIO},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bff30c)}, V_KEY_FAV},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf8b74)}, V_KEY_RECORD},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf8976)}, V_KEY_PLAY},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bfb34c)}, V_KEY_FB},  //快退
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf0bf4)}, V_KEY_FF},   //快进
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bfb14e)}, V_KEY_STOP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf5ba4)}, V_KEY_EPG},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf19e6)}, V_KEY_MENU},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf41be)}, V_KEY_RECALL},  //back
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf916e)}, V_KEY_RED},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf21de)}, V_KEY_GREEN},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf9b64)}, V_KEY_YELLOW},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf6996)}, V_KEY_BLUE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bf6b94)}, V_KEY_PVR_INFO},
#ifdef BISS_HOT_KEY //SUPPORT_BISS
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bfb04f)}, V_KEY_BISS},
#endif	
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0, SET_IRCODE(0x80bfa05f)}, V_KEY_SAT},
    	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fbaa55)}, V_KEY_0},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb10ef)}, V_KEY_1},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb906f)}, V_KEY_2},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb50af)}, V_KEY_3},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb30cf)}, V_KEY_4},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fbb04f)}, V_KEY_5},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb708f)}, V_KEY_6},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fbc43b)}, V_KEY_7},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb8877)}, V_KEY_8},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb0af5)}, V_KEY_9},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fba659)}, V_KEY_LEFT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb46b9)}, V_KEY_RIGHT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb06f9)}, V_KEY_UP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb8679)}, V_KEY_DOWN},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb16e9)}, V_KEY_ENTER},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fbe01f)}, V_KEY_V_UP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fbd02f)}, V_KEY_V_DOWN},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb48b7)}, V_KEY_C_UP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb08f7)}, V_KEY_C_DOWN},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb807f)}, V_KEY_TEXT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fbf00f)}, V_KEY_POWER},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fba45b)}, V_KEY_MUTE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb34cb)}, V_KEY_PAUSE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb847b)}, V_KEY_INFOR},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb58a7)}, V_KEY_EXIT},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb24db)}, V_KEY_TVRADIO},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fbb847)}, V_KEY_FAV},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb38c7)}, V_KEY_EPG},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fbb44b)}, V_KEY_MENU},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb649b)}, V_KEY_RECALL},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fbcc33)}, V_KEY_RED},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb2cd3)}, V_KEY_GREEN},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fbac53)}, V_KEY_YELLOW},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb6c93)}, V_KEY_BLUE},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb7c83)}, V_KEY_PLAY},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb8c73)}, V_KEY_STOP},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb0cf3)}, V_KEY_RECORD},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb02fd)}, V_KEY_PREV},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fbd42b)}, V_KEY_FB},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb53a3)}, V_KEY_FF},
	{{PAN_KEY_TYPE_REMOTE, PAN_KEY_PRESSED, 0,SET_IRCODE(0x04fb4cb3)}, V_KEY_NEXT},
//panel_gos_fd650_key_tab
	{{PAN_KEY_TYPE_PANEL, PAN_KEY_PRESSED, 0, SET_IRCODE(0xffff0080)}, 	V_KEY_POWER},		
	{{PAN_KEY_TYPE_PANEL, PAN_KEY_PRESSED, 0, SET_IRCODE(0xffff0002)}, 	V_KEY_MENU},
	{{PAN_KEY_TYPE_PANEL, PAN_KEY_PRESSED, 0, SET_IRCODE(0xffff0008)}, 	V_KEY_ENTER},
     	{{PAN_KEY_TYPE_PANEL, PAN_KEY_PRESSED, 0, SET_IRCODE(0xffff0020)}, 	V_KEY_EXIT},
	{{PAN_KEY_TYPE_PANEL, PAN_KEY_PRESSED, 0, SET_IRCODE(0xffff0001)},  	V_KEY_UP},
	{{PAN_KEY_TYPE_PANEL, PAN_KEY_PRESSED, 0, SET_IRCODE(0xffff0004)}, 	V_KEY_DOWN},
	{{PAN_KEY_TYPE_PANEL, PAN_KEY_PRESSED, 0, SET_IRCODE(0xffff0010)}, 	V_KEY_LEFT},
	{{PAN_KEY_TYPE_PANEL, PAN_KEY_PRESSED, 0, SET_IRCODE(0xffff0040)}, 	V_KEY_RIGHT},
 #endif
};

ir_key_map_t ir_key_maps[] =
{
	{ROCK00,IRP_NEC,0x807f},
};

static struct pan_hw_info pan_hw_info =
{
	0,/*type_kb : 2; Key board (array) type.*/
	1,/*type_scan : 1; 0: Slot scan, 1: Shadow scan.*/
	1,/*type_key: 1; Key exit or not.*/
	1,/*type_irp: 3; 0: not IRP, 1: NEC, 2: LAB.*/
	0,/*type_mcu: 1; MCU exit or not.*/
	4,/*num_com: 4; Number of com PIN, 0 to 8.*/
	1,/*Position of colon flag, 0 to 7.*/
	1,/*num_scan: 2; Number of scan PIN, 0 to 2.*/
	0,/*rsvd_bits:6; Reserved bits.*/
	0,/*rsvd byte for align pan_info.*/
	{0, HAL_GPIO_O_DIR, 127},/*LATCH PIN.*/
	{0, HAL_GPIO_O_DIR, 24},/*CLOCK PIN.*/
	{1, HAL_GPIO_O_DIR, 23},/*DATA PIN.*/
	{{0, HAL_GPIO_I_DIR, 127},/*SCAN1 PIN.*/
	{0, HAL_GPIO_I_DIR, 127}},/*SCAN2 PIN.*/
	{{0, HAL_GPIO_O_DIR, 127},/*COM1 PIN.*/
	{0, HAL_GPIO_O_DIR, 127},/*COM2 PIN.*/
	{0, HAL_GPIO_O_DIR, 127},/*COM3 PIN.*/
	{0, HAL_GPIO_O_DIR, 127},/*COM4 PIN.*/
	{0, HAL_GPIO_O_DIR, 127},/*COM5 PIN.*/
	{0, HAL_GPIO_O_DIR, 127},/*COM6 PIN.*/
	{0, HAL_GPIO_O_DIR, 127},/*COM7 PIN.*/
	{0, HAL_GPIO_O_DIR, 127}},/*COM8 PIN.*/
	{{0, HAL_GPIO_O_DIR, 127},/*POWER PIN.*/
	{1, HAL_GPIO_O_DIR, 127},/*LOCK PIN.*/
	{0, HAL_GPIO_O_DIR, 127},/*Extend function LBD.*/
	{0, HAL_GPIO_O_DIR, 127}},/*Extend function LBD.*/
	{0, HAL_GPIO_O_DIR, 127},/*rsvd extend function LBD.*/
	300,/*Intv repeat first.*/
	250,/*Intv repeat.*/
	350,/*Intv release, 0: disable release key.*/
	NULL,/*hook_scan() callback.*/
	NULL,/*hook_show() callback.*/
	0,/*p_seg.*/
};

struct pan_configuration pan_config = {&pan_hw_info, bitmap_list_num, bitmap_list};

/*board 01v01 use default pin mux setting is enough.*/
static pin_mux_info pin_mux_array[] =
{
	{XPMU_DOCD_SEL, 0},/*2-31.*/
	{XPMU_UART_SEL, 0},/*2-29.*/
	{XSSI_OUT_SEL2, 0},/*2-28.*/
	{XSC_SEL2, 0},/*2-25.*/
	{HDMI_DEBUG_SEL, 0},/*2-24.*/
	{VOUT_SEL, 0},/*2-22.*/
	{XI2C3_SEL, 1},/*2-21.*/
	{XI2C_SEL, 0},/*2-20.*/
	{XIF_AGC_S2_SEL, 0},/*2-19.*/
	{XUART_TX_SEL, 1},/*2-17.*/
	{XUART_RX_SEL, 1},/*2-16.*/
	{XUSB_RTD_SEL, 0},/*2-15.*/
	{XDISEQC_HV_SEL, 0},/*2-13.*/
	{XDISEQC_OUT_SEL, 0},/*2-12.*/
	{XDISEQC_IN_SEL, 0},/*2-11.*/
//#ifdef GPIO_MUTE_ENABLE//new or change add by yuj
	{XSPDIF_SEL,0},
//#endif
	{XI2C2_SEL, 1},/*2-4.*/
	//Ben 191118#1
	#ifndef WINGDB_DEBUG
	{XSC_SEL, 1},
	#else
	{XSC_SEL, 0},/*2-1.*/	
	#endif
	//

	{XTUN_AGC_QAM_SEL, 0},/*1-20.*/
	{XIF_AGC_QAM_SEL, 1},/*1-19.*/
	{SRGB_PUB_SEL, 0},/*1-18.*/
	{SRGB_SEL2, 0},/*1-17.*/
	{SRGB_SEL1, 0},/*1-16.*/
	{XDISEQC_HV_SEL2, 0},/*1-15.*/
	{XDISEQC_OUT_SEL2, 0},/*1-14.*/
	{XPRGB_QFN_SEL, 0},/*1-13.*/
	{XSC_SEL4, 0},/*1-12.*/
	{XSC_SEL5, 0},/*1-11.*/
	{XPRGB888_SEL, 0},/*1-10.*/
	{XSC_SEL3, 0},/*1-9.*/
	{SSI_OUT_SEL3, 0},/*1-8.*/
	{SPI_MIERR_SEL, 1},/*1-7.*/
	{ASSI_MIERR_SEL4, 0}, /*1-6.*/
	{ASSI_DATA1_SEL4, 0},/*1-5.*/
	{ASSI_SEL4, 0},/*1-4.*/
	{SPI_SEL, 1},/*1-3.*/
	{ASSI_MIERR_SEL3, 0},/*1-2.*/
	{ASSI_DATA1_SEL3, 0},/*1-1.*/
	{ASSI_SEL3, 0},/*1-0.*/
};

static gpio_info_t gpio_array[] =
{
#ifdef GPIO_MUTE_ENABLE    
	{0, HAL_GPIO_O_DIR, 9},/*mute, low:Mute.*/
#else
	{0, HAL_GPIO_O_DIR, -1},/*mute, low:Mute.*/
#endif
	{1, HAL_GPIO_O_DIR, 24},/*PANEL_SCL.*/
	{1, HAL_GPIO_O_DIR, 23},/*PANEL_SDA.*/
	{1, HAL_GPIO_O_DIR, 0},/*GPIO0 I2C SDA for hdmi eddc.*/
	{1, HAL_GPIO_O_DIR, 1},/*GPIO0 I2C SCL for hdmi eddc.*/
};

enum{
	SYS_MUTE_INDEX,
	GPIO_I2C0_SCL_INDEX,
	GPIO_I2C0_SDA_INDEX,
	GPIO_I2C1_SDA_INDEX,
	GPIO_I2C1_SCL_INDEX,
};

front_end_cfg front_end[2];

#ifdef DVBS_SUPPORT
extern INT32 nim_s3501_attach(struct QPSK_TUNER_CONFIG_API *ptrQPSK_Tuner);
extern INT32 nim_s3503_attach(struct QPSK_TUNER_CONFIG_API *ptrQPSK_Tuner);
extern INT32 nim_c3505_attach(struct QPSK_TUNER_CONFIG_API *ptrQPSK_Tuner);
front_end_cfg* front_end_s_cfg(UINT8 tuner_id)
{
	struct QPSK_TUNER_CONFIG_API* qpsk_tuner;
	front_end_cfg* cfg;
	if(tuner_id > 1)
	{
		return NULL;
	}

	cfg = &front_end[tuner_id];
	MEMSET(cfg, 0, sizeof(front_end_cfg));
	cfg->front_end_type = FRONTEND_TYPE_S;
	cfg->sat_id = 2;

	if(0 == tuner_id)
	{
		cfg->lnb_power = NULL;
		cfg->nim_reset = NULL;
		cfg->nim_name = "NIM_S3505_0";
		cfg->tsi_cfg.tsi_select = TSI_DMX_0;
		cfg->tsi_cfg.tsi_id = TSI_SPI_0;
		cfg->tsi_cfg.tsi_attr = 0x8b;

		cfg->nim_config.s_cfg.attach = nim_c3505_attach;
		qpsk_tuner = &cfg->nim_config.s_cfg.qpsk_tuner;
		qpsk_tuner->nim_tuner_init = nim_m3031_init;
		qpsk_tuner->nim_tuner_control = nim_m3031_control;
		qpsk_tuner->nim_tuner_status = nim_m3031_status;
		qpsk_tuner->nim_tuner_command = nim_m3031b_command;
		qpsk_tuner->nim_tuner_gain = nim_m3031_gain;
		qpsk_tuner->tuner_config.c_tuner_base_addr = 0x40;
		qpsk_tuner->config_data.recv_freq_low = 900;
		qpsk_tuner->config_data.recv_freq_high = 2200;
		qpsk_tuner->tuner_config.i2c_type_id = I2C_TYPE_SCB1;
		qpsk_tuner->ext_dm_config.i2c_type_id = I2C_TYPE_SCB1;
		qpsk_tuner->ext_dm_config.i2c_base_addr = 0xe6;
		qpsk_tuner->config_data.qpsk_config = 0xF9;
	}
	else
	{
		cfg->lnb_power = NULL;
		cfg->nim_reset = NULL;
		cfg->nim_name = "NIM_S3505_1";
		cfg->tsi_cfg.tsi_select = TSI_TS_B;
		cfg->tsi_cfg.tsi_id = TSI_SSI2B_0;
		cfg->tsi_cfg.tsi_attr = 0x9b;
		cfg->nim_config.s_cfg.attach = nim_s3501_attach;
		qpsk_tuner = &cfg->nim_config.s_cfg.qpsk_tuner;
		qpsk_tuner->nim_tuner_init = nim_vz7306_init;
		qpsk_tuner->nim_tuner_control = nim_vz7306_control;
		qpsk_tuner->nim_tuner_status = nim_vz7306_status;
		qpsk_tuner->config_data.recv_freq_low = 900;
		qpsk_tuner->config_data.recv_freq_high = 2200;

		/*Fixed Two tuner use the same I2C problem, now tuner2 use I2C_TYPE_GPIO1.*/
		qpsk_tuner->tuner_config.i2c_type_id = I2C_TYPE_GPIO1;
		qpsk_tuner->ext_dm_config.i2c_type_id = I2C_TYPE_GPIO1;
		qpsk_tuner->tuner_config.c_tuner_base_addr = 0xc0;
		qpsk_tuner->ext_dm_config.i2c_base_addr = 0x66;
		qpsk_tuner->config_data.qpsk_config=0x69;
	}
	cfg->lnb_short_det = NULL;
	cfg->tsi_cfg.tsi_spi_tsg_attr = 0x83;
	//cfg->nim_config.s_cfg.tsi_id_m3501a = TSI_SPI_0;
	cfg->nim_config.s_cfg.tsi_id_m3501a = TSI_SSI2B_0;
	cfg->nim_config.s_cfg.tsi_attr_m3501a = 0x8b;

	return cfg;
}
#endif

#ifdef ISDBT_SUPPORT
front_end_cfg* front_end_isdbt_cfg(UINT8 tuner_id)
{
	struct COFDM_TUNER_CONFIG_API* isdbt_tuner;
	front_end_cfg* cfg;

	if(tuner_id > 1)
	{
		return NULL;
	}

	cfg = &front_end[tuner_id];
	MEMSET(cfg, 0, sizeof(front_end_cfg));
	cfg->is_isdbt = 1;
	cfg->front_end_type = FRONTEND_TYPE_T;
	cfg->sat_id = 1;
	cfg->lnb_power = NULL;
	cfg->lnb_short_det = NULL;
	cfg->nim_reset = NULL;
	cfg->tsi_cfg.tsi_id = TSI_SPI_0;
	cfg->tsi_cfg.tsi_attr = 0x87;
	if(tuner_id == 0)
	{
		cfg->tsi_cfg.tsi_select = TSI_TS_A;
	}
	else
	{
		cfg->tsi_cfg.tsi_select = TSI_TS_B;
	}
	cfg->tsi_cfg.tsi_spi_tsg_attr = 0x83;
	isdbt_tuner = &cfg->nim_config.t_cfg.cofdm_tuner;

#if (SYS_DEM_MODULE == COFDM_S3811)
	isdbt_tuner->config_data.flag = 0;/*0:ISDBT mode, 1:DVBT mode.*/
	isdbt_tuner->config_data.memory_size = __MM_COFDM_S3811_ISDBT_BUF_LEN;
	isdbt_tuner->config_data.memory = __MM_COFDM_S3811_ISDBT_ADDR;/*for S3811 ISDBT mode only.*/
	cfg->nim_config.t_cfg.attach = nim_s3811_attach_ext;
	if(1)//tuner_id == 0
	{
		/*S3811 internal demodulator.*/
		cfg->nim_name = "NIM_S3811_0";
		isdbt_tuner->work_mode = NIM_COFDM_SOC_MODE;
	}
	else
	{
		/*S3811 be used as external demodulator.*/
		cfg->nim_name = "NIM_S3811_1";
		isdbt_tuner->work_mode = NIM_COFDM_ONLY_MODE;
		isdbt_tuner->ext_dm_config.i2c_type_id = I2C_TYPE_SCB0;
		isdbt_tuner->ext_dm_config.i2c_base_addr = 0x40;
	}

#else
	#error "SYS_DEM_MODULE had not been defined for ISDBT."
#endif

	isdbt_tuner->tuner_config.i2c_type_id = I2C_TYPE_SCB0;
	isdbt_tuner->ts_mode = NIM_COFDM_TS_SPI_8B;

#if (SYS_TUN_MODULE == MXL136 || SYS_TUN_MODULE == ANY_TUNER)
	{
		isdbt_tuner->tuner_type = MXL136;
		isdbt_tuner->tuner_config.i2c_type_id = I2C_TYPE_SCB0;
		isdbt_tuner->tuner_config.cTuner_Base_Addr = 0xC0;
		isdbt_tuner->config_data.Connection_config = 0x00;/*no I/Q swap.*/
		isdbt_tuner->config_data.Cofdm_Config = 0x03;/*low-if, dirct , if-enable.*/
		isdbt_tuner->config_data.IF_AGC_MAX = 0xff;
		isdbt_tuner->config_data.IF_AGC_MIN = 0x00;
		isdbt_tuner->nim_Tuner_Init = tun_mxl136_init;
		isdbt_tuner->nim_Tuner_Control = tun_mxl136_control;
		isdbt_tuner->nim_Tuner_Status = tun_mxl136_status;
		isdbt_tuner->nim_Tuner_Command = tun_mxl136_command;
		isdbt_tuner->tuner_config.cTuner_Crystal = 24000;/*khz.*/
		isdbt_tuner->tuner_config.cTuner_Ref_DivRatio = 128;
		isdbt_tuner->tuner_config.wTuner_IF_Freq = 4000;
		isdbt_tuner->tuner_config.cTuner_AGC_TOP = 2;/*from 0~7, can be setted by COFDM, ex.disable RF Auto-AGC.*/
		isdbt_tuner->tuner_config.cTuner_Step_Freq = 125;
		isdbt_tuner->tuner_config.cChip = Tuner_Chip_MAXLINEAR;
	}
#elif (SYS_TUN_MODULE == MXL5007)
	{
		isdbt_tuner->config_data.Connection_config = 0x00;/*no I/Q swap.*/
		isdbt_tuner->config_data.Cofdm_Config = 0x03;/*low-if, dirct , if-enable.*/
		isdbt_tuner->config_data.AGC_REF = 0x63;
		isdbt_tuner->config_data.IF_AGC_MAX = 0xff;
		isdbt_tuner->config_data.IF_AGC_MIN = 0x00;
		isdbt_tuner->nim_Tuner_Init = tun_mxl5007_init_ISDBT_mode;
		isdbt_tuner->nim_Tuner_Control = tun_mxl5007_control;
		isdbt_tuner->nim_Tuner_Status = tun_mxl5007_status;
		isdbt_tuner->nim_Tuner_Command = tun_mxl5007_command;
		isdbt_tuner->tuner_config.cTuner_Crystal = 24000;/*Unit: KHz.*/
		isdbt_tuner->tuner_config.wTuner_IF_Freq = 4570;
		isdbt_tuner->tuner_config.cTuner_AGC_TOP = 252;/*Special for MaxLiner.*/
		isdbt_tuner->tuner_config.cChip = Tuner_Chip_MAXLINEAR;
		isdbt_tuner->tuner_config.i2c_type_id = I2C_TYPE_SCB0;
		isdbt_tuner->tuner_config.cTuner_Base_Addr = 0xC0;
		isdbt_tuner->tuner_type = MXL5007;
	}
#else
	#error "SYS_TUN_MODULE had not been defined for ISDBT."
#endif

	if((isdbt_tuner->tuner_config.i2c_type_id & I2C_TYPE_MASK) == I2C_TYPE_GPIO)
	{
		isdbt_tuner->tuner_config.Tuner_Write = i2c_gpio_write;
		isdbt_tuner->tuner_config.Tuner_Read = i2c_gpio_read;
		isdbt_tuner->tuner_config.Tuner_Write_Read = i2c_gpio_write_read;
	}
	else
	{
		isdbt_tuner->tuner_config.Tuner_Write = i2c_scb_write;
		isdbt_tuner->tuner_config.Tuner_Read = i2c_scb_read;
		isdbt_tuner->tuner_config.Tuner_Write_Read = i2c_scb_write_read;
	}

	return cfg;
}
#endif

#ifdef DVBT_SUPPORT
front_end_cfg* front_end_t_cfg(UINT8 tuner_id)
{
	struct COFDM_TUNER_CONFIG_API* t_tuner;
	front_end_cfg* cfg;
	if(tuner_id > 1)
	{
		return NULL;
	}

	cfg = &front_end[tuner_id];
	MEMSET(cfg, 0, sizeof(front_end_cfg));
	cfg->front_end_type = FRONTEND_TYPE_T;
	cfg->is_isdbt = 0;
	cfg->sat_id = 1;
	cfg->lnb_power = NULL;
	cfg->lnb_short_det = NULL;
	cfg->nim_reset = &gpio_array[2];
	cfg->nim_name = "NIM_COFDM_0";
	cfg->tsi_cfg.tsi_id = TSI_SPI_0;
	cfg->tsi_cfg.tsi_attr = 0x87;

	if(tuner_id == 0)
	{
		cfg->tsi_cfg.tsi_select = TSI_TS_A;
	}
	else
	{
		cfg->tsi_cfg.tsi_select = TSI_TS_B;
	}
	cfg->tsi_cfg.tsi_spi_tsg_attr = 0x83;
	t_tuner = &cfg->nim_config.t_cfg.cofdm_tuner;

#if (SYS_DEM_MODULE == COFDM_S3811)
	t_tuner->config_data.flag = 1;/*0:ISDBT mode, 1:DVBT mode.*/
	cfg->nim_config.t_cfg.attach = nim_s3811_attach_ext;
	if(1)//tuner_id == 0
	{
		/*S3811 internal demodulator.*/
		cfg->nim_name = "NIM_S3811_0";
		t_tuner->work_mode = NIM_COFDM_SOC_MODE;
	}
	else
	{
		/*S3811 be used as external demodulator.*/
		cfg->nim_name = "NIM_S3811_1";
		t_tuner->work_mode = NIM_COFDM_ONLY_MODE;
		t_tuner->ext_dm_config.i2c_type_id = I2C_TYPE_SCB0;
		t_tuner->ext_dm_config.i2c_base_addr = 0x40;
	}

#elif (SYS_DEM_MODULE == COFDM_M3101)
	cfg->nim_config.t_cfg.attach_with_name = nim_m3101_dev_attach_ext;
	t_tuner->ext_dm_config.i2c_type_id = I2C_TYPE_SCB0;
	t_tuner->ext_dm_config.i2c_base_addr = 0x40;
	t_tuner->rev_id = M3100_REV_ID;
	t_tuner->config_mode = 1;
	t_tuner->work_mode = NIM_COFDM_ONLY_MODE;
#else
	//#error "SYS_DEM_MODULE had not been defined for DVBT."
#endif

	t_tuner->tuner_config.i2c_type_id = I2C_TYPE_SCB0;
	t_tuner->ts_mode = NIM_COFDM_TS_SPI_8B;
#if (SYS_TUN_MODULE == MXL5007 || SYS_TUN_MODULE == ANY_TUNER)
	t_tuner->config_data.Connection_config = 0x00;/*no I/Q swap.*/
	t_tuner->config_data.Cofdm_Config = 0x03;/*low-if, dirct , if-enable.*/
	t_tuner->config_data.AGC_REF = 0x63;
	t_tuner->config_data.IF_AGC_MAX = 0xff;
	t_tuner->config_data.IF_AGC_MIN = 0x00;
	t_tuner->nim_Tuner_Init = tun_mxl5007_init;
	t_tuner->nim_Tuner_Control = tun_mxl5007_control;
	t_tuner->nim_Tuner_Status = tun_mxl5007_status;
	t_tuner->nim_Tuner_Command = tun_mxl5007_command;
	t_tuner->tuner_config.cTuner_Crystal = 24000;/*Unit: KHz.*/
	t_tuner->tuner_config.wTuner_IF_Freq = 4570;
	t_tuner->tuner_config.cTuner_AGC_TOP = 252;/*Special for MaxLiner.*/
	t_tuner->tuner_config.cChip = Tuner_Chip_MAXLINEAR;
	t_tuner->tuner_config.i2c_type_id = I2C_TYPE_SCB0;
	t_tuner->tuner_config.cTuner_Base_Addr = 0xC0;
	t_tuner->tuner_type = MXL5007;
#elif (SYS_TUN_MODULE == TD1611ALF)
	t_tuner->config_data.Connection_config = 0x00;/*no I/Q swap.*/
	t_tuner->config_data.Cofdm_Config = 0x03;/*low-if, dirct , if-enable.*/
	t_tuner->config_data.AGC_REF = 0x63;
	t_tuner->config_data.IF_AGC_MAX = 0xff;
	t_tuner->config_data.IF_AGC_MIN = 0x00;
	t_tuner->nim_Tuner_Init=tun_td1611alf_init;
	t_tuner->nim_Tuner_Control=tun_td1611alf_control;
	t_tuner->nim_Tuner_Status=tun_td1611alf_status;

	static UINT8 mt352[] = {0x28, 0xA0, 0x00, 0x00, 0xFF, 0x00, 0x00, 0x00, 0x40, 0x00, 0x3, 0xFF, 0x0, 0x0};
	static UINT8 mt353[] = {0x31, 0x62, 0xA1, 0x03, 0x52, 0xFF, 0x1A, 0x0};
	t_tuner->config_data.ptMT352 = mt352;
	t_tuner->config_data.ptMT353 = mt353;
	t_tuner->tuner_config.cTuner_Crystal = 4000;/*khz.*/
	t_tuner->tuner_config.cTuner_Base_Addr = 0xC0;
	t_tuner->tuner_config.cChip=Tuner_Chip_INFINEON;
	t_tuner->tuner_config.cTuner_Ref_DivRatio = 24;
	t_tuner->tuner_config.wTuner_IF_Freq = 36160;
	t_tuner->tuner_config.cTuner_AGC_TOP = 2;/*from 0~7, can be setted by COFDM, ex.disable RF Auto-AGC.*/
	t_tuner->tuner_config.cTuner_Step_Freq = 166;
	t_tuner->tuner_type = TD1611ALF;
#elif (SYS_TUN_MODULE == MXL5005)
	t_tuner->config_data.Connection_config = 0x00;/*no I/Q swap.*/
	t_tuner->config_data.Cofdm_Config = 0x03;/*low-if, dirct , if-enable.*/
	t_tuner->config_data.AGC_REF = 0x53;
	t_tuner->config_data.IF_AGC_MAX = 0xff;
	t_tuner->config_data.IF_AGC_MIN = 0x00;
	t_tuner->nim_Tuner_Init = tun_mxl5005_init;
	t_tuner->nim_Tuner_Control = tun_mxl5005_control;
	t_tuner->nim_Tuner_Status = tun_mxl5005_status;
	t_tuner->tuner_config.cTuner_Crystal = 16;/*Unit: MHz.*/
	t_tuner->tuner_config.wTuner_IF_Freq = 4570;
	t_tuner->tuner_config.cTuner_AGC_TOP = 252;
	t_tuner->tuner_config.cChip = Tuner_Chip_MAXLINEAR;
	t_tuner->tuner_config.i2c_type_id = I2C_TYPE_SCB0;
	t_tuner->tuner_config.cTuner_Base_Addr = 0xc6;
	//t_tuner->ts_mode = NIM_COFDM_TS_SSI;
	t_tuner->tuner_type = MXL5005;
#elif (SYS_TUN_MODULE == NM120)
	t_tuner->config_data.Connection_config = 0x00;/*no I/Q swap.*/
	t_tuner->config_data.Cofdm_Config = 0x03;/*low-if, dirct , if-enable.*/
	t_tuner->config_data.AGC_REF = 0x63;
	t_tuner->config_data.IF_AGC_MAX = 0xff;
	t_tuner->config_data.IF_AGC_MIN = 0x00;
	t_tuner->nim_Tuner_Init = tun_nm120_init;
	t_tuner->nim_Tuner_Control = tun_nm120_control;
	t_tuner->nim_Tuner_Status = tun_nm120_status;
	t_tuner->tuner_config.cTuner_Crystal = 24000;/*khz.*/
	t_tuner->tuner_config.cTuner_Ref_DivRatio = 24;
	t_tuner->tuner_config.wTuner_IF_Freq = 4570;
	t_tuner->tuner_config.cTuner_AGC_TOP = 5;
	t_tuner->tuner_config.cTuner_Step_Freq = 166;
	t_tuner->tuner_config.cChip=Tuner_Chip_MAXLINEAR;
	t_tuner->tuner_config.i2c_type_id = I2C_TYPE_SCB0;
	t_tuner->tuner_config.cTuner_Base_Addr = 0xce;
	t_tuner->tuner_type = NM120;
#elif (SYS_TUN_MODULE == RT820T)
	t_tuner->config_data.Connection_config = 0x00;/*no I/Q swap.*/
	t_tuner->config_data.Cofdm_Config = 0x03;/*low-if, dirct , if-enable.*/
	t_tuner->config_data.AGC_REF = 0x63;
	t_tuner->config_data.IF_AGC_MAX = 0xff;
	t_tuner->config_data.IF_AGC_MIN = 0x00;
	t_tuner->nim_Tuner_Init=tun_rt820_init;
	t_tuner->nim_Tuner_Control = tun_rt820_control;
	t_tuner->nim_Tuner_Status = tun_rt820_status;
	t_tuner->tuner_config.cTuner_Crystal = 4000;/*khz.*/
	t_tuner->tuner_config.cTuner_Ref_DivRatio = 24;
	t_tuner->tuner_config.wTuner_IF_Freq = 3570;/*3570 for 6M mode, 4570 for 8M/7M mmode;.*/
	t_tuner->tuner_config.cTuner_AGC_TOP = 5;
	t_tuner->tuner_config.cTuner_Step_Freq = 166;
	t_tuner->tuner_config.cChip=Tuner_Chip_MAXLINEAR;
	t_tuner->tuner_config.i2c_type_id = I2C_TYPE_SCB0;
	//t_tuner->tuner_config.cTuner_Base_Addr = 0xc0;
	t_tuner->tuner_type = RT820T;
#elif (SYS_TUN_MODULE == MXL603)
	t_tuner->config_data.Connection_config = 0x00;/*no I/Q swap.*/
	t_tuner->config_data.Cofdm_Config = 0x03;/*low-if, dirct , if-enable.*/
	t_tuner->config_data.AGC_REF = 0x63;
	t_tuner->config_data.IF_AGC_MAX = 0xff;
	t_tuner->config_data.IF_AGC_MIN = 0x00;
	t_tuner->nim_Tuner_Init = tun_mxl603_init;
	t_tuner->nim_Tuner_Control = tun_mxl603_control;
	t_tuner->nim_Tuner_Status = tun_mxl603_status;
	t_tuner->nim_Tuner_Command = tun_mxl603_command;
	t_tuner->tuner_config.cTuner_Crystal = 16;/*Unit: MHz.*/
	t_tuner->tuner_config.wTuner_IF_Freq = 4570;
	t_tuner->tuner_config.cTuner_AGC_TOP = 252;/*Special for MaxLiner.*/
	t_tuner->tuner_config.cChip = Tuner_Chip_MAXLINEAR;
	t_tuner->tuner_config.i2c_type_id = I2C_TYPE_SCB0;
	t_tuner->tuner_config.cTuner_Base_Addr = 0xC0;
	t_tuner->tuner_type = MXL603;
#elif (SYS_TUN_MODULE == AT810)
	t_tuner->nim_Tuner_Init = tun_AT810_init;
	t_tuner->nim_Tuner_Control = tun_AT810_control;
	t_tuner->nim_Tuner_Status = tun_AT810_status;
	t_tuner->nim_Tuner_Command = tun_AT810_command;
	t_tuner->config_data.Cofdm_Config = 0x13;/*BBAGC enabled, positive slope + 0IF modulation.*/
	t_tuner->config_data.Connection_config = 0x00;/* no I/Q swap.*/
	t_tuner->config_data.AGC_REF = 0x63;
	t_tuner->config_data.IF_AGC_MAX = 0xff;/*max DAC value.*/
	t_tuner->config_data.IF_AGC_MIN = 0x01;
	t_tuner->tuner_config.cTuner_Crystal = 24000;
	t_tuner->tuner_config.cTuner_Base_Addr = (0x61<<1);
	t_tuner->tuner_config.cTuner_Ref_DivRatio = 24;
	t_tuner->tuner_config.wTuner_IF_Freq = 0;
	t_tuner->tuner_config.cTuner_AGC_TOP = 2;
	t_tuner->tuner_config.cTuner_Step_Freq = 125;
	t_tuner->tuner_config.cChip = 0;
	t_tuner->tuner_type = AT810;
#elif (SYS_TUN_MODULE == DB5515)
	t_tuner->config_data.Connection_config = 0x00;/*no I/Q swap.*/
	t_tuner->config_data.Cofdm_Config = 0x03;/*low-if, dirct , if-enable.*/
	t_tuner->config_data.AGC_REF = 0x63;
	t_tuner->config_data.IF_AGC_MAX = 0xff;
	t_tuner->config_data.IF_AGC_MIN = 0x00;
	t_tuner->nim_Tuner_Init = tun_db5515_init;
	t_tuner->nim_Tuner_Control = tun_db5515_control;
	t_tuner->nim_Tuner_Status = tun_db5515_status;
	t_tuner->nim_Tuner_Command = NULL;
	t_tuner->tuner_config.cTuner_Crystal = 27000;/*Unit: KHz.*/
	t_tuner->tuner_config.wTuner_IF_Freq = 4000;
	t_tuner->tuner_config.cTuner_AGC_TOP = 252;/*Special for MaxLiner.*/
	t_tuner->tuner_config.cChip = Tuner_Chip_INFINEON;
	t_tuner->tuner_config.i2c_type_id = I2C_TYPE_SCB0;
	t_tuner->tuner_config.cTuner_Base_Addr = 0xC2;
	t_tuner->tuner_type = DB5515;
#else
	#error "SYS_TUN_MODULE had not been defined for DVBT."
#endif

	if((t_tuner->tuner_config.i2c_type_id & I2C_TYPE_MASK) == I2C_TYPE_GPIO)
	{
		t_tuner->tuner_config.Tuner_Write = i2c_gpio_write;
		t_tuner->tuner_config.Tuner_Read = i2c_gpio_read;
		t_tuner->tuner_config.Tuner_Write_Read = i2c_gpio_write_read;
	}
	else
	{
		t_tuner->tuner_config.Tuner_Write = i2c_scb_write;
		t_tuner->tuner_config.Tuner_Read = i2c_scb_read;
		t_tuner->tuner_config.Tuner_Write_Read = i2c_scb_write_read;
	}

	return cfg;
}
#endif

#ifdef DVBC_SUPPORT

enum DVBC_MODE_TYPE
{
	DVBC_MODE_J83AC = 0,
	DVBC_MODE_J83B = 1,		
};

void m32_pin_mux_set_qam_select(UINT8 dvbc_mode)
{
	UINT32 data_long=0x00;

	//QAM
    if(dvbc_mode == DVBC_MODE_J83B)
    {   // for J83B mode  (6CH[20:19]=2b'00;)
        data_long=(*(volatile UINT32 *)(0xB800006c));
        data_long = data_long & 0xFFE7FFFF;
        *(volatile UINT32 *)(0xB800006c) = data_long;
    }
    else //(dvbc_mode == DVBC_MODE_J83AC)
    {   // for J83AC mode (6CH[20:19]=2b'01;)
        data_long=(*(volatile UINT32 *)(0xB800006c));
        data_long = data_long & 0xFFE7FFFF;
        *(volatile UINT32 *)(0xB800006c) = data_long | 0x00080000;//bit19=1
    }
	
#ifdef SUPPORT_TWO_TUNER
	 //QAM2
	 if(dvbc_mode == DVBC_MODE_J83B)
	 {	 // for J83B mode  (6CH[22:21]=2b'00;)
		 data_long=(*(volatile UINT32 *)(0xB800006c));
		 data_long = data_long & 0xFF9FFFFF;
		 *(volatile UINT32 *)(0xB800006c) = data_long | 0x00800000;//bit23=1
	 }
	 else //(dvbc_mode == DVBC_MODE_J83AC)
	 {	 // for J83AC mode (6CH[22:21]=2b'01;)
		 data_long=(*(volatile UINT32 *)(0xB800006c));
		 data_long = data_long & 0xFF9FFFFF;
		 *(volatile UINT32 *)(0xB800006c) = data_long | 0x00A00000;//bit23=1,bit21=1
	 }
#endif
}

void front_end_c_get_qam_config(UINT8 dvbc_mode,UINT32 nim_clk,struct DEMOD_CONFIG_ADVANCED* p_demod_config)
{	
	UINT32 data_long=0x00;
	
	if(dvbc_mode == DVBC_MODE_J83B)
	{
		p_demod_config->qam_buffer_len= __MM_NIM_DVBC_BUFFER_LEN;	
		p_demod_config->qam_buffer_addr=__MM_NIM_DVBC_BUFFER_ADDR;
		p_demod_config->qam_config_advanced = NIM_DVBC_J83B_MODE | nim_clk;  // j83ac, 54m sampleclk/dspclk
	}
	else if(dvbc_mode == DVBC_MODE_J83AC)
	{
		p_demod_config->qam_buffer_len= 0x00;	
		p_demod_config->qam_buffer_addr=0x00;
		p_demod_config->qam_config_advanced = NIM_DVBC_J83AC_MODE |nim_clk;  // j83ac, 54m sampleclk/dspclk
	}
	
	//set sample clock (604H[0]: 0 for 27M, 1 for 54M)
    if((NIM_SAMPLE_CLK_54M & p_demod_config->qam_config_advanced) == NIM_SAMPLE_CLK_54M)
    { //54M, double cyrstal clock for sample clock        
        data_long=(*(volatile UINT32 *)(0xB8000604));
        data_long = data_long | 0x00000001;
        *(volatile UINT32 *)(0xB8000604) = data_long;
    }
    else
    { //27M, same as crystal clock        
        data_long=(*(volatile UINT32 *)(0xB8000604));        
		data_long = data_long & 0xFFFFFFFE;
        *(volatile UINT32 *)(0xB8000604) = data_long;
    }
	
	m32_pin_mux_set_qam_select(dvbc_mode);
}
//new or change add by yuj -s
extern INT32 nim_s3281_dvbc_attach(struct QAM_TUNER_CONFIG_API * ptrqam_tuner);
extern INT32 tun_r836_dvbc_init(UINT32 *tuner_id, struct QAM_TUNER_CONFIG_EXT * ptrTuner_Config);
extern INT32 tun_r836_status(UINT32 tuner_id, UINT8 *lock);
extern INT32 tun_r836_dvbc_control(UINT32 tuner_id, UINT32 freq, UINT32 sym, UINT8 AGC_Time_Const, UINT8 _i2c_cmd);
extern INT32 tun_r836_command(UINT32 tuner_id, INT32 cmd, UINT32 param);
extern INT32 tun_atbm2040_init(UINT32* tuner_id, struct QAM_TUNER_CONFIG_EXT * ptrTuner_Config);
extern INT32 tun_atbm2040_status(UINT32 tuner_id, UINT8 *lock);
extern INT32 tun_atbm2040_control(UINT32 tuner_id, UINT32 freq, UINT32 sym, UINT8 AGC_Time_Const, UINT8 _i2c_cmd);
extern INT32 tun_atbm2040_command(UINT32 tuner_id, INT32 cmd, UINT32 param);
extern INT32 tun_atbm253_init(UINT32* tuner_id, struct QAM_TUNER_CONFIG_EXT * ptrTuner_Config);
extern INT32 tun_atbm253_status(UINT32 tuner_id, UINT8 *lock);
extern INT32 tun_atbm253_control(UINT32 tuner_id, UINT32 freq, UINT32 sym, UINT8 AGC_Time_Const, UINT8 _i2c_cmd);
extern INT32 tun_atbm253_command(UINT32 tuner_id, INT32 cmd, UINT32 param);
front_end_cfg* front_end_c_cfg(UINT8 tuner_id,UINT32 type)
{    
    struct QAM_TUNER_CONFIG_API*  c_tuner;
    front_end_cfg* cfg;   
    UINT32 mode_value=DVBC_MODE_J83AC;
	UINT32 data_long=0x00;
	
    if(tuner_id > 1)
     return NULL;

    cfg = &front_end[tuner_id];
    MEMSET(cfg, 0, sizeof(front_end_cfg));
    cfg->front_end_type = FRONTEND_TYPE_C;    
    cfg->sat_id = 1;
    cfg->lnb_power = NULL;
    cfg->lnb_short_det = NULL;    
    cfg->is_isdbt = 0;

    cfg->nim_name = "NIM_S3281_0";
	cfg->nim_reset = NULL;
	cfg->tsi_cfg.tsi_id 	= TSI_SPI_0;
	cfg->tsi_cfg.tsi_select = TSI_TS_A;
	cfg->tsi_cfg.tsi_attr	= 0x8b;
	cfg->tsi_cfg.tsi_spi_tsg_attr = 0x83;
	cfg->nim_config.c_cfg.attach = nim_s3281_dvbc_attach;
	c_tuner = &cfg->nim_config.c_cfg.qam_tuner;
	
	// config for tuner MXL603
	if(type == RT836)
	{
		c_tuner->tuner_config_data.IF_AGC_MAX	= 0xFE;
		c_tuner->tuner_config_data.IF_AGC_MIN		= 0x01;
		c_tuner->tuner_config_data.RF_AGC_MAX	= 0xBA;
		c_tuner->tuner_config_data.RF_AGC_MAX	= 0x2A;
		c_tuner->tuner_config_data.AGC_REF		= 0x80;


		c_tuner->tuner_config_ext.c_tuner_special_config	=0x01;
		c_tuner->tuner_config_ext.c_chip				= TUNER_CHIP_NXP;
		c_tuner->tuner_config_ext.c_tuner_agc_top		= 1;//7; /*1 for single AGC, 7 for dual AGC */
		c_tuner->tuner_config_ext.c_tuner_base_addr 	=  0x74;//0x74;//0x96;  //0xc0;
		c_tuner->tuner_config_ext.c_tuner_crystal		= 16;
		c_tuner->tuner_config_ext.c_tuner_ref_div_ratio 	= 64;
		c_tuner->tuner_config_ext.c_tuner_step_freq 		= 62.5;

		c_tuner->tuner_config_ext.w_tuner_if_freq_j83a=5070;//5000;
		c_tuner->tuner_config_ext.w_tuner_if_freq_j83b=5070;
		c_tuner->tuner_config_ext.w_tuner_if_freq_j83c=5070;

		//c_tuner->tuner_config_ext.c_tuner_reopen=0x00;
		c_tuner->tuner_config_data.c_tuner_tsi_setting = NIM_0_SPI_0;
		//c_tuner->tuner_config_ext.w_tuner_if_j83ac_type = 0x01;
		c_tuner->tuner_config_ext.w_tuner_if_freq = c_tuner->tuner_config_ext.w_tuner_if_freq_j83a; // 5000, for 8M; 5380 for 6M.
		c_tuner->tuner_config_ext.i2c_type_id = I2C_TYPE_SCB1;
		c_tuner->tuner_config_ext.c_tuner_special_config = 0x01;
		c_tuner->nim_tuner_init 		= tun_r836_dvbc_init;
		c_tuner->nim_tuner_control 	= tun_r836_dvbc_control;
		c_tuner->nim_tuner_status 	= tun_r836_status;
		
		typedef INT32 (*tun_cmd_funf)(UINT32 tuner_id, INT32 cmd, INT32 *param);
		c_tuner->nim_tuner_command = (tun_cmd_funf)tun_r836_command;
}
	else if(type == ATBM2040)
	{
		c_tuner->tuner_config_data.IF_AGC_MAX	= 0xFE;
		c_tuner->tuner_config_data.IF_AGC_MIN		= 0x01;
		c_tuner->tuner_config_data.RF_AGC_MAX	= 0xBA;
		c_tuner->tuner_config_data.RF_AGC_MAX	= 0x2A;
		c_tuner->tuner_config_data.AGC_REF		= 0x80;


		c_tuner->tuner_config_ext.c_tuner_special_config	=0x01;
		c_tuner->tuner_config_ext.c_chip				= TUNER_CHIP_NXP;
		c_tuner->tuner_config_ext.c_tuner_agc_top		= 1;//7; /*1 for single AGC, 7 for dual AGC */
		c_tuner->tuner_config_ext.c_tuner_base_addr 	=  0xC0;//0x74;//0x96;  //0xc0;
		c_tuner->tuner_config_ext.c_tuner_crystal		= 16;
		c_tuner->tuner_config_ext.c_tuner_ref_div_ratio 	= 64;
		c_tuner->tuner_config_ext.c_tuner_step_freq 		= 62.5;

		c_tuner->tuner_config_ext.w_tuner_if_freq_j83a	=5000;//5000;
		c_tuner->tuner_config_ext.w_tuner_if_freq_j83b	=5070;
		c_tuner->tuner_config_ext.w_tuner_if_freq_j83c	=5070;

		//c_tuner->tuner_config_ext.c_tuner_reopen=0x00;
		c_tuner->tuner_config_data.c_tuner_tsi_setting = NIM_0_SPI_0;
		//c_tuner->tuner_config_ext.w_tuner_if_j83ac_type = 0x01;
		c_tuner->tuner_config_ext.w_tuner_if_freq = c_tuner->tuner_config_ext.w_tuner_if_freq_j83a; // 5000, for 8M; 5380 for 6M.
		c_tuner->tuner_config_ext.i2c_type_id = I2C_TYPE_SCB1;
		c_tuner->tuner_config_ext.c_tuner_special_config = 0x01;
		c_tuner->nim_tuner_init	 	= tun_atbm2040_init;
		c_tuner->nim_tuner_control 	= tun_atbm2040_control;
		c_tuner->nim_tuner_status 	= tun_atbm2040_status;
		
		typedef INT32 (*tun_cmd_funf)(UINT32 tuner_id, INT32 cmd, INT32 *param);
		c_tuner->nim_tuner_command = (tun_cmd_funf)tun_atbm2040_command;
	}
	else if(type == ATBM253)
	{
		c_tuner->tuner_config_data.IF_AGC_MAX	= 0xFE;
		c_tuner->tuner_config_data.IF_AGC_MIN		= 0x01;
		c_tuner->tuner_config_data.RF_AGC_MAX	= 0xBA;
		c_tuner->tuner_config_data.RF_AGC_MAX	= 0x2A;
		c_tuner->tuner_config_data.AGC_REF		= 0x80;


		c_tuner->tuner_config_ext.c_tuner_special_config	=0x01;
		c_tuner->tuner_config_ext.c_chip				= TUNER_CHIP_NXP;
		c_tuner->tuner_config_ext.c_tuner_agc_top		= 1;//7; /*1 for single AGC, 7 for dual AGC */
		c_tuner->tuner_config_ext.c_tuner_base_addr 	=  0xF8;//0x74;//0x96;  //0xc0;
		c_tuner->tuner_config_ext.c_tuner_crystal		= 16;
		c_tuner->tuner_config_ext.c_tuner_ref_div_ratio 	= 64;
		c_tuner->tuner_config_ext.c_tuner_step_freq 		= 62.5;

		c_tuner->tuner_config_ext.w_tuner_if_freq_j83a	=5000;//5000;
		c_tuner->tuner_config_ext.w_tuner_if_freq_j83b	=5070;
		c_tuner->tuner_config_ext.w_tuner_if_freq_j83c	=5070;

		//c_tuner->tuner_config_ext.c_tuner_reopen=0x00;
		c_tuner->tuner_config_data.c_tuner_tsi_setting = NIM_0_SPI_0;
		//c_tuner->tuner_config_ext.w_tuner_if_j83ac_type = 0x01;
		c_tuner->tuner_config_ext.w_tuner_if_freq = c_tuner->tuner_config_ext.w_tuner_if_freq_j83a; // 5000, for 8M; 5380 for 6M.
		c_tuner->tuner_config_ext.i2c_type_id = I2C_TYPE_SCB1;
		c_tuner->tuner_config_ext.c_tuner_special_config = 0x01;
		c_tuner->nim_tuner_init	 	= tun_atbm253_init;
		c_tuner->nim_tuner_control 	= tun_atbm253_control;
		c_tuner->nim_tuner_status 	= tun_atbm253_status;
		
		typedef INT32 (*tun_cmd_funf)(UINT32 tuner_id, INT32 cmd, INT32 *param);
		c_tuner->nim_tuner_command = (tun_cmd_funf)tun_atbm253_command;
	}
	front_end_c_get_qam_config(mode_value, NIM_SAMPLE_CLK_27M, &(c_tuner->dem_config_advanced));

	//0xb800006C bit23:QAMS2_SPI_SEL, 0:S2 select(default), 1:QAM select
	data_long=(*(volatile UINT32 *)(0xB800006c));        
	data_long = data_long | (1<<23);
	*(volatile UINT32 *)(0xB800006c) = data_long;

    return cfg;
}
#endif
//new or change add by yuj -e

struct scart_init_param scart_param =
{
 	0,
	0,
	(UINT32)NULL,
	0,
	0x94,
};

sci_cfg sci_config[] =
{
	{SCI_FOR_RS232, 115200, SCI_PARITY_EVEN},
	{SCI_FOR_MDM, 115200, SCI_PARITY_EVEN},
};

i2c_cfg i2c_config[6] =
{
	{I2C_TYPE_SCB0, 100000, 1, NULL, NULL},
	{I2C_TYPE_SCB1, 100000, 1, NULL, NULL},
	{I2C_TYPE_SCB2, 100000, 1, NULL, NULL},
	{I2C_TYPE_SCB3, 100000, 1, NULL, NULL},
	{I2C_TYPE_GPIO0, 100000, 1, &gpio_array[GPIO_I2C0_SDA_INDEX], &gpio_array[GPIO_I2C0_SCL_INDEX]},
	{I2C_TYPE_GPIO1, 100000, 1, &gpio_array[GPIO_I2C1_SDA_INDEX], &gpio_array[GPIO_I2C1_SCL_INDEX]},
};

extern void board_ddr_priority_init(void);

board_cfg* advance_cfg(board_cfg* cfg)
{
	if(NULL == cfg)
	{
		return NULL;
	}

	cfg->chip_param.mem_gpio_enabled = FALSE;
	cfg->chip_param.ci_power_ctl_enabled = FALSE;
#if (SYS_NETWORK_MODULE == NET_ALIETHMAC)
	cfg->chip_param.ali_ethmac_enabled = FALSE;
#endif

#if 1//(defined SHOW_ALI_DEMO_ON_SCREEN)
	cfg->adv_cfg_para.hdcp_disable = TRUE;
#else
	cfg->adv_cfg_para.hdcp_disable = TRUE;//TRUE;//new or change add by yuj
#endif

	cfg->adv_cfg_para.i2c_for_eddc = I2C_TYPE_GPIO1;
#ifdef AUDIO_DESCRIPTION_SUPPORT
	cfg->adv_cfg_para.audio_description_support = TRUE;
#else
	cfg->adv_cfg_para.audio_description_support = FALSE;
#endif

	cfg->adv_cfg_para.sys_mute_gpio = gpio_array[SYS_MUTE_INDEX].position;
	cfg->adv_cfg_para.ext_mute_mode = MUTE_BY_GPIO;
	cfg->adv_cfg_para.sys_mute_polar = gpio_array[SYS_MUTE_INDEX].polar;
	cfg->adv_cfg_para.snd_output_chip_type = 1;

#ifdef HD_SUBTITLE_SUPPORT
	cfg->adv_cfg_para.hd_subtitle_support = TRUE;
#else
	cfg->adv_cfg_para.hd_subtitle_support = FALSE;
#endif

	cfg->adv_cfg_para.tve_full_current_mode = FALSE;
	cfg->adv_cfg_para.tve_tbl = tve_table_total;
	cfg->adv_cfg_para.tve_adjust = g_sd_tve_adjust_table;
	cfg->adv_cfg_para.tve_adjust_adv = tve_sd_adjust_table_adv;

#ifdef SUPPORT_PACKET_26
	cfg->adv_cfg_para.ttx_packet_26_support = TRUE;
#else
	cfg->adv_cfg_para.ttx_packet_26_support = FALSE;
#endif

#ifdef TTX_SUB_PAGE
	cfg->adv_cfg_para.ttx_sub_page = TRUE;
#else
	cfg->adv_cfg_para.ttx_sub_page = FALSE;
#endif

#if (defined MULTI_CAS)
	cfg->adv_cfg_para.cas_type = CAS_CONAX;
	#ifdef SUPPORT_CAS9
	cfg->adv_cfg_para.cas9_support = TRUE;
	#else
	cfg->adv_cfg_para.cas9_support = FALSE;
	#endif
	cfg->adv_cfg_para.invert_detect = 1;
#endif

#if defined(_VMX_CA_ENABLE_) || defined(_VMX_CA_STD_ENABLE_)
	cfg->adv_cfg_para.invert_detect = 1;/*M3515 SMC SB board : 0, DB board : 1.*/
#endif

#ifdef SUPPORT_AFD_SCALE
	cfg->adv_cfg_para.afd_scale_support = TRUE;
#else
	cfg->adv_cfg_para.afd_scale_support = FALSE;
#endif

#ifdef H264_SUPPORT_MULTI_BANK
	cfg->adv_cfg_para.h264_support_mulit_bank = TRUE;
#else
	cfg->adv_cfg_para.h264_support_mulit_bank = FALSE;
#endif

#ifdef CHANCHG_VIDEOTYPE_SUPPORT
	cfg->adv_cfg_para.chanchg_video_type_support = TRUE;
#else
	cfg->adv_cfg_para.chanchg_video_type_support = FALSE;
#endif

#ifdef AVC_SUPPORT_UNIFY_MEM
	cfg->adv_cfg_para.avc_unify_mem_support = TRUE;
#else
	cfg->adv_cfg_para.avc_unify_mem_support = FALSE;
#endif
	cfg->adv_cfg_para.ce_api_enabled = TRUE;

	/*add for setting priority for IP access DDR.*/
	board_ddr_priority_init();

	return cfg;
}

board_cfg* get_board_config(void)
{
	UINT8 i = 0;

	MEMSET(&board_config, 0, sizeof(board_cfg));
	board_config.pin_mux_count = ARRAY_SIZE(pin_mux_array);
	board_config.all_gpio_count = ARRAY_SIZE(gpio_array);
	board_config.mem_gpio_enabled = MEM_GPIO_ENABLED;
	board_config.pin_mux_array = pin_mux_array;
	board_config.all_gpio_array = gpio_array;

	board_config.ddr_power_ctl = NULL;
	board_config.sys_power = NULL;
	board_config.mute = &gpio_array[SYS_MUTE_INDEX];
	board_config.usb_power = NULL;
	board_config.fp_standby = NULL;
#ifdef DVBT_SUPPORT
	board_config.scart_tvsat_switch = NULL;
	board_config.scart_aspect = NULL;
	board_config.scart_tv_fb = NULL;
#else
	board_config.scart_tvsat_switch = NULL;
	board_config.scart_aspect = NULL;
	board_config.scart_tv_fb = NULL;
#endif
	board_config.scart_power = NULL;
	board_config.scart_vcr_switch = NULL;
	board_config.scart_vcr_detech = NULL;
	board_config.smc_5v_ctl = NULL;
	board_config.ata2lan_cs = NULL;

#ifdef SDIO_SUPPORT
	board_config.sdio_detect = NULL;
	board_config.sdio_lock = NULL;
	board_config.sdio_cs = NULL;
#endif

#ifdef DVBS_SUPPORT
	board_config.front_end_cfg[0] = front_end_s_cfg(0);
	#ifdef SUPPORT_TWO_TUNER
	board_config.front_end_cfg[1] = front_end_s_cfg(1);
	#endif
#elif defined(ISDBT_SUPPORT)
	board_config.front_end_cfg[0] = front_end_isdbt_cfg(0);
#elif defined(DVBT_SUPPORT)
	board_config.front_end_cfg[0] = front_end_t_cfg(0);
#elif defined(DVBC_SUPPORT)	
	board_config.front_end_cfg[0] = front_end_c_cfg(0,ATBM253);//new or change add by yuj
#endif

	board_config.libc_printf_uart_id = SCI_FOR_RS232;
	board_config.sci_config[0] = &sci_config[0];
#ifndef DUAL_ENABLE
	board_config.sci_config[1] = NULL;
#endif

#ifdef GPRS_UART_SUPPORT
	board_config.sci_config[0]->sci_parity = SCI_PARITY_NONE;
#endif

	for(i=0; i<6; i++)
	{
		board_config.i2c_config[i] = &i2c_config[i];
	}
	board_config.i2c_gpio_num = 2;
	board_config.i2c_scb_num = 4;

	/*M3811_DB_01V01 has no SCART IC.*/
	board_config.scart_param = NULL;
	board_config.scart_attach = NULL;
	board_config.pan_config = &pan_config;
	board_config.pan_i2c_id_set = NULL;//new or change add by yuj
	board_config.pan_i2c_id = I2C_TYPE_GPIO0;//billy/20170526
	board_config.pan_attach = pan_fd650_gp_attach;///new or change add by yuj
	board_config.flash_type = 0;
	board_config.rfm_attach = NULL;
	board_config.rfm_i2c_id = I2C_TYPE_SCB1;
	board_config.key_map = g_itou_key_tab;
	board_config.ir_key_maps = ir_key_maps;
	board_config.key_map_cnt = sizeof(g_itou_key_tab)/(sizeof(struct ir_key_map_t));

	return advance_cfg(&board_config);
}

int AliRegSetBits32(
	unsigned int Address,
	unsigned int StartBitIdx, /* From 0 to 31*/
	unsigned int EndBitIdx,/* From 0 to 31, should be bigger than StartBitIdx*/
	unsigned int BitsValue
)
{
	unsigned int Value = 0;
	unsigned int Mask = 0;
	unsigned int Idx = 0;

	for (Idx = StartBitIdx; Idx <= EndBitIdx; Idx++)
	{
		Mask |= (1 << Idx);
	}

	BitsValue <<= StartBitIdx;
	BitsValue &= Mask;

	/*Clean Value conrresponding bits to 0.*/
	Mask = (~Mask);
	Value = ALI_HW_REG_R32(Address);
	Value &= Mask;

	/*Set BitsValue to Value.*/
	Value |= BitsValue;

	/*Set Value to HW.*/
	ALI_HW_REG_W32(Address, Value);

	return 0;
}

unsigned int AliRegGetBits32
(
	unsigned int Address,
	unsigned int StartBitIdx,/*From 0 to 31.*/
	unsigned int EndBitIdx/*From 0 to 31, should be bigger than StartBitIdx.*/
)
{
	unsigned int Value = 0;
	unsigned int Mask = 0;
	unsigned int Idx = 0;

	for (Idx = StartBitIdx; Idx <= EndBitIdx; Idx++)
	{
		Mask |= (1 << Idx);
	}

	Value = ALI_HW_REG_R32(Address);
	Value &= Mask;
	Value >>= StartBitIdx;

	return Value;
}

void phy_chip_setting(void)
{
	unsigned int tmp_u32 = 0;

	/*reset phy.*/
	tmp_u32 = *(volatile unsigned int *)(0xB8000430);
	tmp_u32 |= (1 << 2);/*GPIO2 PHY reset enable.*/
	*(volatile unsigned int *)(0xB8000430) = tmp_u32;

	tmp_u32 = *(volatile unsigned int *)(0xB8000058);
	tmp_u32 |= (1 << 2);/*GPIO2 PHY reset output.*/
	*(volatile unsigned int *)(0xB8000058) = tmp_u32;

	tmp_u32 = *(volatile unsigned int *)(0xB8000054);
	tmp_u32 |= (1 << 2);/*GPIO2 PHY reset output 1.*/
	*(volatile unsigned int *)(0xB8000054) = tmp_u32;

	tmp_u32 = *(volatile unsigned int *)(0xB8000054);
	tmp_u32 &= ~(1 << 2);/*GPIO2 PHY reset output 0.*/
	*(volatile unsigned int *)(0xB8000054) = tmp_u32;

	tmp_u32 = *(volatile unsigned int *)(0xB8000054);
	tmp_u32 |= (1 << 2);/*GPIO2 PHY reset output 1.*/
	*(volatile unsigned int *)(0xB8000054) = tmp_u32;
}

void gos_gpio_set_tuner_reset(void)//new or change add by yuj
{
#if 1
	HAL_GPIO_BIT_DIR_SET(9, HAL_GPIO_O_DIR);
	HAL_GPIO_BIT_SET(9, 1);
	osal_delay(100000);
	HAL_GPIO_BIT_SET(9, 0);
	osal_delay(100000);
	HAL_GPIO_BIT_SET(9, 1);
#else
	HAL_GPIO_BIT_DIR_SET(16, HAL_GPIO_O_DIR);
	HAL_GPIO_BIT_SET(16, 1);
	osal_delay(100000);
	HAL_GPIO_BIT_SET(16, 0);
	osal_delay(100000);
	HAL_GPIO_BIT_SET(16, 1);
#endif
}
static UINT8 b_gos_gpio_is_signal_light_red = 0xFF;//new or change add by yuj
void gos_gpio_set_signal_light_red( void )//new or change add by yuj
{
	//SET_DWORD(0xb8000054, GET_DWORD(0xb8000054)&(~(0x1<<16)));	
	if(b_gos_gpio_is_signal_light_red  != 1)
	{
		HAL_GPIO_BIT_DIR_SET(16, HAL_GPIO_O_DIR);
		HAL_GPIO_BIT_SET(16, 0);
		b_gos_gpio_is_signal_light_red = 1;
	}
}
void gos_gpio_set_signal_light_green ( void )//new or change add by yuj
{
	//SET_DWORD(0xb8000054, GET_DWORD(0xb8000054)|(0x1<<16));	
	if(b_gos_gpio_is_signal_light_red  != 0)
	{
		HAL_GPIO_BIT_DIR_SET(16, HAL_GPIO_O_DIR);
		HAL_GPIO_BIT_SET(16, 1);
		b_gos_gpio_is_signal_light_red = 0;
	}
}

